### ISSUE TITLE
PettingZoo

### ISSUE THREAD

**Issue by jkterry1** [opendilab/DI-engine#153]
Hey, for all your multi-agent environments have you considered using the pettingzoo API?

https://github.com/Farama-Foundation/PettingZoo

**Comment by PaParaZz1** [comment]
> Hey, for all your multi-agent environments have you considered using the pettingzoo API?
> 
> https://github.com/Farama-Foundation/PettingZoo

Yes, we plan to move some our existing multi-agent RL environments (like MPE) to pettingzoo API this month. 

For SMAC and multi-agent mujoco, there are plenty of work to polish their code, do you have will to transfer them together? Or any other comments about them?

BTW, you can have a look about our new MARL env [GoBigger](https://github.com/opendilab/GoBigger).

**Comment by PaParaZz1** [comment]
We have integrated MPE of pettingzoo in DI-engine. For more environments in pettingzoo, one can add another issue and we will keep track of it.
