### ISSUE TITLE
when I use Multi-GPUs to train my model，RuntimeError: Caught RuntimeError in replica 0 on device 0

### ISSUE THREAD

**Issue by ZYeGao** [opendilab/DI-engine#162]
when I use Multi-GPUs to train my model for Gobigger, the error happened: RuntimeError: Caught RuntimeError in replica 0 on device 0

The detail in https://github.com/opendilab/Gobigger-Explore/issues/3

**Comment by PaParaZz1** [comment]
> when I use Multi-GPUs to train my model for Gobigger, the error happened: RuntimeError: Caught RuntimeError in replica 0 on device 0
> 
> The detail in [opendilab/Gobigger-Explore#3](https://github.com/opendilab/Gobigger-Explore/issues/3)

OK, I have noticed @jayyoung0802 and we will track this problem in `Gobigger-Explore` repo, so I close this issue.
