### ISSUE TITLE
Add slimevolleygym into dizoo

### ISSUE THREAD

**Issue by zxzzz0** [opendilab/DI-engine#17]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [x] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc]()
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable (N/A)

[slimevolleygym](https://github.com/hardmaru/slimevolleygym) is a pong-like physics game env from the open source community. It follows standard OpenAI gym interface. Naive PPO self-play achieves scores of `-0.371 ± 1.085` in `slimeVolley-v0` env against built-in AI [report](https://github.com/hardmaru/slimevolleygym/blob/master/TRAINING.md#results-summary).  
It would be good to benchmark opendilab's league training and see if it can generate higher results.

**Comment by PaParaZz1** [comment]
@LuciusMos PPO(with RNN and without RNN), on policy training, `slimeVolley-v0` env

**Comment by zxzzz0** [comment]
To clarify let use league training with 3 roles (MA, ME, LE) rather than pure self-play training. There is also a built-in AI and do not use that for training. After training is finished we can evaluate agents against built-in AI and compare the numeric numbers with the report above.

**Comment by zxzzz0** [comment]
@PaParaZz1 Could you please create an issue for the following PR?
