### ISSUE TITLE
League Evaluation Metric

### ISSUE THREAD

**Issue by zxzzz0** [opendilab/DI-engine#18]
Added this issue as suggested by @PaParaZz1.

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [x] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc]()
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable: N/A

[TrueSkill](https://trueskill.org/) is a ranking metric developed by Microsoft for game matchmaking. Unlike ELO which just measures one agent's strength, TrueSkill can measure both strength and stability. Each player starts with `mu=25.000` and `sigma=8.333`. Former one (`mu`) measures strength and the latter one (`sigma`) measures stability. After receiving payoffs of one matching, `mu` and `sigma` will be updated accordingly from the TrueSkill API. Final agent's score can be defined as `mu - 3 * sigma` to take both strength and stability into consideration.

Currently this metric is missing in the league demo. It would be better to add it.

**Comment by PaParaZz1** [comment]
TrueSkill demo result in tensorboard <img width="1159" alt="Screen Shot 2021-08-10 at 3 23 42 PM" src="https://user-images.githubusercontent.com/33195032/128827660-0b5d6282-b080-48a8-9b70-a06add037e1a.png">

**Comment by zxzzz0** [comment]
This issue has been solved in PR #22.
