### ISSUE TITLE
Invalid output of `ding --help`

### ISSUE THREAD

**Issue by sailxjx** [opendilab/DI-engine#182]
Currently when I use `ding --help`, it prints out the following:

```
usage: ding [-h] [--cfg CFG] [--seed SEED] [--device DEVICE]

optional arguments:
  -h, --help       show this help message and exit
  --cfg CFG
  --seed SEED
  --device DEVICE
```

which is not the expected help information.

I searched the code and found that this behaviour is caused by [This line of code](https://github.com/opendilab/DI-engine/blob/main/ding/entry/application_entry_trex_collect_data.py#L94), please try to fix this.

**Comment by PaParaZz1** [comment]
This problem has been fixed, and we will refactor CLI with sub-command in the future version.
