### ISSUE TITLE
Visualize Training Progression

### ISSUE THREAD

**Issue by zxzzz0** [opendilab/DI-engine#19]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [x] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc]()
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable: N/A

RL training can be unstable and fall into local optimal solution easily. Visualization and monitoring metrics are therefore extremely important. Assume there are 3 roles in league training (MA, ME, LE). It would be better to visualize metrics for each of these roles over the training time.

**Comment by PaParaZz1** [comment]
This issue is also figured out in #18, the visualization result is like:

![image](https://user-images.githubusercontent.com/33195032/131977203-698c1ecb-02e1-446d-b56c-c343435858c2.png)
