### ISSUE TITLE
Image and dict observation spaces support by BC and GAIL implementations

### ISSUE THREAD

**Issue by akmandor** [opendilab/DI-engine#194]
In the README, could you provide the information on the observation/action spaces that are supported by each algorithm?

Specifically, do BC and GAIL implementations support image and dict observation spaces?

**Comment by davide97l** [comment]
Hello @akmandor. 
As for GAIL: observations space can be both a 1D array or a 3D array and action space is a 1D array. Observations space is not a dict, it can be a numpy array or a tensor.
For a quick example you can run the following commands:

```
cd dizoo/box2d/lunarlander/config
ding -m serial -c lunarlander_dqn_config.py   # train lunarlander expert DQN
python lunarlander_dqn_gail_config.py  # collect expert data and train lunarlander GAIL
```

BC is still under development and you can follow its progress in this PR: https://github.com/opendilab/DI-engine/pull/110
Note that we have not tested GAIL with 3D observations yet, but we have extensively tested it on Mujoco and Box2D envs.
