### ISSUE TITLE
PettingZoo for SMAC

### ISSUE THREAD

**Issue by jkterry1** [opendilab/DI-engine#227]
As a follow up to #153, you guys don't need to separately support the SMAC API; you can just use the PettingZoo API since SMAC supports it and it's fairly heavily used.

**Comment by PaParaZz1** [comment]
Our SMAC implementations have some modifications like two player battle, so we can't transfer it directly, maybe we can discuss about it after refactoring in next version. 

BTW, we show great interest in `classic` part of pettingzoo, and we will add some examples in March.
