### ISSUE TITLE
Is the performance of re-implemented GAIL compareble with the results in original paper?

### ISSUE THREAD

**Issue by huang-fuxian** [opendilab/DI-engine#260]
Hi, I want to use your code as a baseline, however I am not sure if your code is good enough to match the results in original paper.
Could you please provide more information, like training figures?

**Comment by davide97l** [comment]
Hi @huang-fuxian, we are currently benchmarking our GAIL implementation to be sure it matches the results provided in the original paper. We will update you about our outcome in a couple of days. Here is our benchmark result on Mujoco Hopper environment (~3500) using SAC as expert: https://di-engine-docs.readthedocs.io/en/latest/hands_on/gail.html#benchmark

**Comment by huang-fuxian** [comment]
Thanks a lot, @davide97l . I will try it.
