### ISSUE TITLE
v2版本中，可以实现不同worker上的collector将收集到的信息传送到learner所在的worker上吗

### ISSUE THREAD

**Issue by lzh2918** [opendilab/DI-engine#308]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```

**Comment by PaParaZz1** [comment]
we have implemented this pattern now, you can refer to doc of this [part](https://di-engine-docs.readthedocs.io/zh_CN/latest/distributed/index_zh.html#id4).
