### ISSUE TITLE
gtrxl

### ISSUE THREAD

**Issue by hlsafin** [opendilab/DI-engine#319]
How to run gtrxl with ppo policy? can someone provide an example?

**Comment by zxzzz0** [comment]
Try this one https://github.com/opendilab/DI-engine/blob/main/dizoo/bsuite/config/serial/memory_len/memory_len_15_r2d2_gtrxl_config.py

**Comment by PaParaZz1** [comment]
You can try gtrxl with R2D2 according to above mentioned link. 

As for gtrxl with PPO, if necessary, we will add corresponding implementation. Which RL environment do you want to use gtrxl with ppo, such as some discrete action envs like lunarlander?

**Comment by hlsafin** [comment]
Hmmm oddly enough, I tried that link and it was giving me some error. I will try to run it again and see what the error was. I am just trying to test it out on atari env at the moment.

**Comment by hlsafin** [comment]
from easydict import EasyDict
from torch import dropout

memory_len_r2d2_gtrxl_config = dict(
    exp_name='memory_len_15_r2d2_gtrxl_seed0',
    env=dict(
        collector_env_num=1,
        evaluator_env_num=1,
        n_evaluator_episode=20,
        env_id='PongNoFrameskip-v4',  # this environment configuration is 30 'memory steps' long
        #env_id ='cartpole_swingup/0',
        frame_stack=4,
        
        stop_value=1.,
        manager=dict(shared_memory=False, )
    ),
    policy=dict(
        cuda=True,
        priority=True,
        priority_IS_weight=True,
        
        model=dict(


            obs_shape=4,
            action_shape=6,
            memory_len=0,
            hidden_size=64,
            gru_bias=1.,  # gru_bias: 0. to 2.,
            
        ),
        discount_factor=0.997,  # discount_factor: 0.97-0.99
        nstep=3,
        burnin_step=0,
        unroll_len=35,  # unroll_len >= seq_len
        seq_len=35,  # for better converge should be seq_len > 'memory steps' = 30
        learn=dict(
            update_per_collect=8,
            batch_size=64,
            learning_rate=0.0005,
            target_update_theta=0.001,
            init_memory='zero',  # 'zero' or 'old', how to initialize the transformer memory
        ),
        collect=dict(each_iter_n_sample=32, env_num=1,n_sample=5 ),
        eval=dict(env_num=1, evaluator=dict(eval_freq=10, )),
        other=dict(
            eps=dict(
                type='exp',
                start=0.95,
                end=0.05,
                decay=1e5,
            ),
            replay_buffer=dict(replay_buffer_size=50000, ),
        ),
    ),
)
memory_len_r2d2_gtrxl_config = EasyDict(memory_len_r2d2_gtrxl_config)
main_config = memory_len_r2d2_gtrxl_config
memory_len_r2d2_gtrxl_create_config = dict(

    env=dict(
        type='atari',
        import_names=['dizoo.atari.envs.atari_env'],
    ),
    env_manager=dict(type='subprocess'),
    policy=dict(type='r2d2_gtrxl'),
)
memory_len_r2d2_gtrxl_create_config = EasyDict(memory_len_r2d2_gtrxl_create_config)
create_config = memory_len_r2d2_gtrxl_create_config

if __name__ == "__main__":

    from ding.entry import serial_pipeline
    serial_pipeline((main_config, create_config), seed=0)



and I got this error 
 File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'GTrXLDiscreteHead' object has no attribute 'dropout'

**Comment by PaParaZz1** [comment]
> and I get this error
> 
> File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in **getattr** raise ModuleAttributeError("'{}' object has no attribute '{}'".format( torch.nn.modules.module.ModuleAttributeError: 'GTrXLDiscreteHead' object has no attribute 'dropout'

Maybe your config is wrong, you can check it by comparing it with [our atari config](https://github.com/opendilab/DI-engine/blob/main/dizoo/atari/config/serial/pong/pong_r2d2_gtrxl_config.py), i.e. for Atari env, you need to indicate 3D `obs_shape`

**Comment by hlsafin** [comment]
I did that, and I get the same issue. 
`from easydict import EasyDict
from torch import dropout

memory_len_r2d2_gtrxl_config = dict(
    exp_name='memory_len_15_r2d2_gtrxl_seed0',
    env=dict(
        collector_env_num=1,
        evaluator_env_num=1,
        n_evaluator_episode=20,
        env_id='PongNoFrameskip-v4',  # this environment configuration is 30 'memory steps' long
        #env_id ='cartpole_swingup/0',
        frame_stack=4,
        
        stop_value=1.,
        manager=dict(shared_memory=False, )
    ),
    policy=dict(
        cuda=True,
        priority=True,
        priority_IS_weight=True,
        
        model=dict(


            obs_shape=[4, 84, 84],
            action_shape=6,
            memory_len=0,
            hidden_size=64,
            gru_bias=1.,  # gru_bias: 0. to 2.,
            
        ),
        discount_factor=0.997,  # discount_factor: 0.97-0.99
        nstep=3,
        burnin_step=0,
        unroll_len=35,  # unroll_len >= seq_len
        seq_len=35,  # for better converge should be seq_len > 'memory steps' = 30
        learn=dict(
            update_per_collect=8,
            batch_size=64,
            learning_rate=0.0005,
            target_update_theta=0.001,
            init_memory='zero',  # 'zero' or 'old', how to initialize the transformer memory
        ),
        collect=dict(each_iter_n_sample=32, env_num=1,n_sample=5 ),
        eval=dict(env_num=1, evaluator=dict(eval_freq=10, )),
        other=dict(
            eps=dict(
                type='exp',
                start=0.95,
                end=0.05,
                decay=1e5,
            ),
            replay_buffer=dict(replay_buffer_size=50000, ),
        ),
    ),
)
memory_len_r2d2_gtrxl_config = EasyDict(memory_len_r2d2_gtrxl_config)
main_config = memory_len_r2d2_gtrxl_config
memory_len_r2d2_gtrxl_create_config = dict(

    env=dict(
        type='atari',
        import_names=['dizoo.atari.envs.atari_env'],
    ),
    env_manager=dict(type='subprocess'),
    policy=dict(type='r2d2_gtrxl'),
)
memory_len_r2d2_gtrxl_create_config = EasyDict(memory_len_r2d2_gtrxl_create_config)
create_config = memory_len_r2d2_gtrxl_create_config

if __name__ == "__main__":
    # or you can enter `ding -m serial -c memory_len_15_r2d2_gtrxl_config.py -s 0`
    from ding.entry import serial_pipeline
    serial_pipeline((main_config, create_config), seed=0)`

**Comment by PaParaZz1** [comment]
What kind of crash error you get, can you offer more details like the error traceback?

**Comment by hlsafin** [comment]
I can't really see, I have everything on that docker file, it trains for a while then after several hours it exits, so I am assuming maybe it was a memory leak then sigkill was called? possibly. Were you able to run training in that environment with no issues after a very long period of time?

**Comment by PaParaZz1** [comment]
Maybe your problem is OOM, due to the huge replay buffer of R2D2-GTrXL, you can try to rerun your experiment with smaller `replay_buffer_size`. In our experiment about R2D2-GTrXL in Atari (training curve is in [here](https://di-engine-docs.readthedocs.io/en/polish-1.0/12_policies/gtrxl.html#benchmark)), it usually needs more than 50~60GB of RAM, you can monitor the usage of RAM.

**Comment by hlsafin** [comment]
I had my replay buffer at 1000, and also doesn't the replay buffer fill up fairly quickly in the beginning? or does it still fill up several hours later that would cause this OOM. Because my understanding was that if it can work for the first 3 hours, why all of a sudden does it break after that? make no sense to me.

**Comment by PaParaZz1** [comment]
For R2D2-GTrXL, each element in replay buffer is a `train_sample`, i.e., a list of transition of length `unroll_len`, so it will not be full at one. I think you should monitor the usage of RAM in your experiment first, you can utilize some tools like [this](https://linuxconfig.org/how-to-monitor-ram-usage-on-linux)

**Comment by hlsafin** [comment]
![image](https://user-images.githubusercontent.com/36808133/169682024-fcd3f573-d7c1-4b48-b480-4be45c5db8b4.png)

This is what I get after 1.6 million env_time_steps, and the mean reward is still around -20, I use the same config as what was mentioned before except I brought the experience replay buffer to 1000 vs 10,000 before. Does this look right to you?

**Comment by PaParaZz1** [comment]
I have rerun the `pong_r2d2_gtrxl.py` with `buffer_size` 10000 and 1000, here is the naive result:
<img width="718" alt="Screen Shot 2022-05-25 at 2 55 56 PM" src="https://user-images.githubusercontent.com/33195032/170199936-d54dacd7-9b54-4fd7-ad02-c6768b631fc4.png">
You can see the experiment with `buffer_size` 1000 (blue curve) indeed shows more poor performance and until 2M env step it begins to rise. But the experiment with `buffer_size` 10000 exhibits the similar result with our previous experiment, so there is no bug in our implementation and you need a larger replay buffer.

BTW, the memory utilization of these two experiment are shown as follows:
- `buffer_size` 10000, max usage 40.0GB:
<img width="1145" alt="Screen Shot 2022-05-25 at 3 07 40 PM" src="https://user-images.githubusercontent.com/33195032/170201731-706f4b1d-c6f6-47b8-a25c-75bf3f2a8972.png">

- `buffer_size` 1000, max usage 9.8GB:
<img width="1119" alt="Screen Shot 2022-05-25 at 3 09 19 PM" src="https://user-images.githubusercontent.com/33195032/170203553-79265342-6cbf-4e18-be44-405cd31542a2.png">

**Comment by hlsafin** [comment]
Okay wow, thank you for the demonstration, I didn't realize that the buffer size played such a huge role. I'm currently trying to tackle Montezuma revenge with 8 GPUs, how do I make them run r2d2gtrx on multi-GPUs with data-parallel (i'm currently doing ddp). What sort of config do you recommend? I currently am running it on 1 gpu with  memory len at 256, and unroll_len 95,seq_len = 90, and not much learning is happening, I'm wondering if it's my setup or r2d2gtrxl just isn't able to solve this problem?

**Comment by hlsafin** [comment]
Okay, Because I was under the impression that games like minigrid, which this approach shouldn't have any issue solving,  and Montezuma revenge are similar in that they both have sparse rewards. Maybe I am incorrect here.

Also, I tried running pong with the approach, and I still wasn't able to get your reward. It stays around -19 for 5 million time steps.

**Comment by Sino-Huang** [comment]
@PaParaZz1 Greeting, a quick question, is there a easy way for me to concatenate a Conv2D network before the GTrXl network because it looks like I cannot directly use GTrXl for Atari environment due to obs_shape, also there is no obs_shape parameter in GTrXl.
