### ISSUE TITLE
Suggestion on unittest for ding/utils/plot.py

### ISSUE THREAD

**Issue by HansBug** [opendilab/DI-engine#323]
[The unit test here](https://github.com/opendilab/DI-engine/blob/main/ding/utils/tests/test_plot.py#L35) can just check whether the file was produced successfully, but in actual, image files frequently have issues with generation (for example, some styles, element rendering failure, etc.). As a result, such a test does not function properly:

Here's an idea:

1. Please test matplotlib image content using unit testing (see https://github.com/matplotlib/pytest-mpl).

2. Use an image similarity unit test, such as https://github.com/Apkawa/pytest-image-diff.

3. In addition, files will be generated under the project directory, which could have unintended consequences on the Git workspace and may be added to the repository in later git add commands. For unit tests, please use the mocked path, such as [isolated_directory in hbutils](https://hansbug.github.io/hbutils/main/api_doc/testing/isolated.html#isolated-directory).

**Comment by zxzzz0** [comment]
What is the advantage of doing this over directly comparing the raw data that will be plotted?

**Comment by HansBug** [comment]
> What is the advantage of doing this over directly comparing the raw data that will be plotted?

When comparing two plotted graphs, this is acceptable. However, if the pictures are not data-based (such as UML or other graphics), image-similarity-based comparison have to be used.

**Comment by PaParaZz1** [comment]
@Weiyuhong-1998 please polish related unittest according to this issue.
