### ISSUE TITLE
Issues w.r.t the refactored logging system

### ISSUE THREAD

**Issue by ZHZisZZ** [opendilab/DI-engine#328]
I used to use `2> error.txt` to redirect only error message, which leaves other information on terminal.
But after [logging system refactoriation](https://github.com/opendilab/DI-engine/commit/c811b2a5bba847a05eb373ba4d104b35c330e51b), `2> error.txt` will redirect all the outputs, including evaluator and collector outputs and so on.

**Comment by HansBug** [comment]
In fact, by default, log information is output to the stderr stream (see [logging.StreamHandler](https://docs.python.org/3/library/logging.handlers.html#streamhandler), which is the most-frequently-used log handler).

After this refactor, all the log information (including `RichHandler` and native `StreamHandler`) will be printed to `sys.stderr`.

In addition, we need to clarify one thing in specific applications. The log output on the terminal is used for real-time viewing by users. If the log for archiving is required, it should be configured in the program to output it to the corresponding in the file (see [Logger.addHandler](https://docs.python.org/3/library/logging.html#logging.Logger.addHandler) and [FileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.FileHandler)).
