### ISSUE TITLE
Can you provide some examples of multi-agent rl ?

### ISSUE THREAD

**Issue by wuzeyang** [opendilab/DI-engine#405]
Although, many multi-agent rl algorithms are implemented here. But there are very few examples of application shown here.

**Comment by PaParaZz1** [comment]
You can try multi-agent rl algorithm in the following env:
- [SMAC](https://github.com/opendilab/DI-engine/tree/main/dizoo/smac)
- [MA mujoco](https://github.com/opendilab/DI-engine/tree/main/dizoo/multiagent_mujoco)

You can also add more information about what kind of MARL environments and applications you want

**Comment by wuzeyang** [comment]
> You can try multi-agent rl algorithm in the following env:
> 
> * [SMAC](https://github.com/opendilab/DI-engine/tree/main/dizoo/smac)
> * [MA mujoco](https://github.com/opendilab/DI-engine/tree/main/dizoo/multiagent_mujoco)
> 
> You can also add more information about what kind of MARL environments and applications you want

**Comment by wuzeyang** [comment]
Thank you for your reply.
