### ISSUE TITLE
Import error for TREX

### ISSUE THREAD

**Issue by CurtisYin** [opendilab/DI-engine#409]
Hello, I'm a beginner in IRL and I want to reproduce the results of TREX algorithm by running "dizoo/mujoco/entry/mujoco_trex_main.py" in the repo. But there is an ImportError: cannot import name 'serial_pipeline_trex_onpolicy' from 'ding.entry'. I think it is because there is no corresponding file named "serial_entry_trex.py" which contains functions 'serial_pipeline_trex_onpolicy' and 'serial_pipeline_trex'. 
Can someone help me to solve that, thank you.

**Comment by PaParaZz1** [comment]
This bug has been fixed in #410, add you can have a try.
