### ISSUE TITLE
How to use ObsNormEnv？

### ISSUE THREAD

**Issue by zyz109429** [opendilab/DI-engine#419]
I would like to ask about the details of the use of state standardization.

State is a one-dimensional vector composed of three eigenvectors, where the first eigenvector has a value range of about 0-40, for example: [2, 1, 8, 12, 12, 4, 1, 2]. The range of the second eigenvector is approximately 0-11, for example: [2.3, 1.4, 0.2, 0.9, 8.4, 7.1, 8.3, 9.4]. The third eigenvector is the one-hot vector. Example: [0,0,1,0,0,0,0,0].

In this case, can I use ObsNormEnv directly? I don't think so.

So I would like to ask your advice, thank you very much.

**Comment by PaParaZz1** [comment]
`ObsNormEnv` is suitable for normal image state like that in Atari and Procgen env.

For your case, it is important to unify data range for different state vectors, which is better for getting more smooth gradient scale. You have already know the data range, so there are two basic methods you can try:
- max-min method, norm your state into 0-1 range by `(x-min)/(max-min)`
- discretization method, divide the whole range into several discrete bins (for example, 0-40 can be divided into 8 bins with interval 5), and if a value is located in bins 3 (i.e. 10-15), it should be transformed into a one-hot vector `[0,0,1,0,0,0,0,0]`. This method is effective when fine-grained state information is not necessary.

**Comment by zyz109429** [comment]
Okay, thank you for your advice.
