### ISSUE TITLE
Example of MAPPO

### ISSUE THREAD

**Issue by carlorop** [opendilab/DI-engine#422]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:

Would it be possible to get an example of training an MAPPO in a sample MA environment?

**Comment by PaParaZz1** [comment]
You can refer to #405 

And we are improving multi-agent example of mpe env in [pettingzoo](https://github.com/opendilab/DI-engine/tree/main/dizoo/petting_zoo), it will also be released in a week.
