### ISSUE TITLE
May be you should add readme on pypi site?

### ISSUE THREAD

**Issue by HansBug** [opendilab/DI-engine#426]
## What do I find?

Look at here: https://pypi.org/project/DI-engine/

It says

> The author of this package has not provided a project description

## Why this is not okay?

If I open the pypi page, I will be confused that what is it? :confused: 

## How to solve this problem

These information should be configured in `setup.py`. So just take a look at [the implement in treevalue](https://github.com/opendilab/treevalue/blob/main/setup.py#L53).

After that, the content in README will be visible on pypi site, like [the treevalue](https://pypi.org/project/treevalue/). (Some links are down, I'm fixing :smile_cat: )

**Comment by PaParaZz1** [comment]
I have add this description and it will take effect in next package release.
