### ISSUE TITLE
安装DI-engine的问题

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#431]
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
print(torch.__version__, sys.version, sys.platform)
1.11.0+cu113 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
  ```
我已经安装了torch1.11.0+cu113 ,但是在使用`pip install DI-engine`时，却在下载不带cuda的torch-1.10.0-cp38-cp38-win_amd64.whl

这和手册里面不一致：
https://di-engine-docs.readthedocs.io/zh_CN/latest/01_quickstart/installation_zh.html

```
在安装好 CUDA 之后，当您在安装 DI-engine 的依赖项时，会自动获取和安装带有 Nvidia CUDA 加速的 PyTorch。
```
安装完成后，导致如下冲突：
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.12.0+cu113 requires torch==1.11.0, but you have torch 1.10.0 which is incompatible.
torchaudio 0.11.0+cu113 requires torch==1.11.0, but you have torch 1.10.0 which is incompatible.
tianshou 0.4.9 requires gym>=0.23.1, but you have gym 0.20.0 which is incompatible.
nbconvert 6.5.0 requires jinja2>=3.0, but you have jinja2 2.11.3 which is incompatible.
```
卸载torch，升级gym，重新安装torchtorch1.11.0+cu113,导致如下冲突：
```
di-engine 0.4.0 requires gym==0.20.0, but you have gym 0.25.1 which is incompatible.
di-engine 0.4.0 requires torch<=1.10.0,>=1.1.0, but you have torch 1.11.0+cu113 which is incompatible.
```

di-engine对版本要求太固定了。
```

**Comment by zjowowen** [comment]
Thanks for your advice. We are currently working on fixing pytorch dependencies to a higher version, 1.11.0 and 1.12.0.
By the way, torch<=1.10.0 is tested, while torch>1.10.0 has not been tested yet.

However, generally, it is not a big issue for most of the code in DI-engine. If you must run DI-engine with torch==1.11.0, it would be fine I guess.

You can temporarily disable the pytorch version requirement in the "setup.py".
Another pytorch dependency is located in DI-treetensor. You have to install it and disable its requirement in "requirement.txt".

Or, you could install torch==1.10.1+cu113 by downloading manually, "https://download.pytorch.org/whl/cu113/torch-1.10.1%2Bcu113-cp38-cp38-win_amd64.whl".

**Comment by jaried** [comment]
> Thanks for your advice. We are currently working on fixing pytorch dependencies to a higher version, 1.11.0 and 1.12.0. By the way, torch<=1.10.0 is tested, while torch>1.10.0 has not been tested yet.
> 
> However, generally, it is not a big issue for most of the code in DI-engine. If you must run DI-engine with torch==1.11.0, it would be fine I guess.
> 
> You can temporarily disable the pytorch version requirement in the "setup.py". Another pytorch dependency is located in DI-treetensor. You have to install it and disable its requirement in "requirement.txt".
> 
> Or, you could install torch==1.10.1+cu113 by downloading manually, "https://download.pytorch.org/whl/cu113/torch-1.10.1%2Bcu113-cp38-cp38-win_amd64.whl".

因为我的生产环境装了太多的运行库，因此，存在版本冲突的情况下，我先用annaconda给di单独建立一个环境来练习，暂时还不迁入生产。

**Comment by zjowowen** [comment]
We are also currently working on update gym from 0.20.0 to 0.25.0. Some tests for compatability are being conducted. It would be soon for this update.

**Comment by PaParaZz1** [comment]
We have upgrades pytorch(1.1.0-1.12.1) and gym(0.25.0) version in above-mentioned PR
