### ISSUE TITLE
How to get more info data in reward model?

### ISSUE THREAD

**Issue by xuehui1991** [opendilab/DI-engine#435]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [+] documentation request
    + [+] new feature request
- [+] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [+] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [+] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```
<img width="450" alt="image" src="https://user-images.githubusercontent.com/6280746/182990900-ed502d4f-a753-47c5-ab32-3e7e2df622ca.png">

Dear all, 
I just try to customize a reward model by Di-engine, however I found we only can get those data(as input of collect_data funciton):

<img width="836" alt="image" src="https://user-images.githubusercontent.com/6280746/182991152-193805e0-3227-424e-aee1-2cba30f19880.png">

My question is how to get more data in reward model? such as the 'info' from env return.
Looking for replay and thank you.

**Comment by xuehui1991** [comment]
> * [ ]  I have marked all applicable categories:
>   
>   * [ ]  exception-raising bug
>   * [ ]  RL algorithm bug
>   * [ ]  system worker bug
>   * [ ]  system utils bug
>   * [ ]  code design/refactor
>   * [+] documentation request
>   * [+] new feature request
> * [+] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
> * [+] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
> * [+] I have mentioned version numbers, operating system and environment, where applicable:
>   ```python
>   import ding, torch, sys
>   print(ding.__version__, torch.__version__, sys.version, sys.platform)
>   ```
> 
> <img alt="image" width="450" src="https://user-images.githubusercontent.com/6280746/182990900-ed502d4f-a753-47c5-ab32-3e7e2df622ca.png">
> 
> Dear all, I just try to customize a reward model by Di-engine, however I found we only can get those data(as input of collect_data funciton):
> 
> <img alt="image" width="836" src="https://user-images.githubusercontent.com/6280746/182991152-193805e0-3227-424e-aee1-2cba30f19880.png">
> 
> My question is how to get more data in reward model? such as the 'info' from env return. Looking for replay and thank you.

**Comment by xuehui1991** [comment]
@zjowowen

**Comment by PaParaZz1** [comment]
In most of DI-engine's policies, we use `process_transition` method to pass necessary information (e.g. [link](https://github.com/opendilab/DI-engine/blob/main/ding/policy/dqn.py#L316)), so we don't add other attributes of env timestep like `info` into transition.

If you want to add this, briefly, there are two methods:
- modify `process_transition` method of policy you used, add `info` into transition, and it will be also available in reward_model
- add the information you want into `obs` or `reward` field, and process them in reward_model

**Comment by xuehui1991** [comment]
Thank you and I already solve this problem!
