### ISSUE TITLE
cannot import name 'HPPO' from 'ding.model'

### ISSUE THREAD

**Issue by ddharshan** [opendilab/DI-engine#436]
Why I couldn't import HPPO from ding?
This is the comment I used in the Jupiter notebook   **from ding.model import HPPO**

**Comment by puyuan1996** [comment]
First of all, thanks for your question.

I'm not sure what HPPO you're referring to here, I'm guessing it refers to a hybrid action space algorithm [ HPPO](https://arxiv.org/abs/1903.01344). If so, you can refer to our runnable entry [config](https://github.com/opendilab/DI-engine/blob/main/dizoo/gym_hybrid/config/gym_hybrid_hppo_config.py) on the [gym_hybrid](https://github.com/opendilab/DI-engine/blob/main/dizoo/gym_hybrid/envs/gym_hybrid_env.py) environment. 

Our HPPO implementation is fused with the original [PPO](https://arxiv.org/abs/1707.06347), and they share the same policy and model python module. You need to specifically look at the `action_space='hybrid'` part of the PPO[ policy](https://github.com/opendilab/DI-engine/blob/main/ding/policy/ppo.py) and [model](https://github.com/opendilab/DI-engine/blob/main/ding/model/template/vac.py) code. Specifically, the key part of HPPO policy is [here](https://github.com/opendilab/DI-engine/blob/63861b9357bb14f399f1df64f5d0b04a79d84dc9/ding/policy/ppo.py#L220), the key part of HPPO model is[ here](https://github.com/opendilab/DI-engine/blob/63861b9357bb14f399f1df64f5d0b04a79d84dc9/ding/model/template/vac.py#L152). 

Hope this answers your doubts.

**Comment by ddharshan** [comment]
> First of all, thanks for your question.
> 
> I'm not sure what HPPO you're referring to here, I'm guessing it refers to a hybrid action space algorithm [ HPPO](https://arxiv.org/abs/1903.01344). If so, you can refer to our runnable entry [config](https://github.com/opendilab/DI-engine/blob/main/dizoo/gym_hybrid/config/gym_hybrid_hppo_config.py) on the [gym_hybrid](https://github.com/opendilab/DI-engine/blob/main/dizoo/gym_hybrid/envs/gym_hybrid_env.py) environment.
> 
> Our HPPO implementation is fused with the original [PPO](https://arxiv.org/abs/1707.06347), and they share the same policy and model python module. You need to specifically look at the `action_space='hybrid'` part of the PPO[ policy](https://github.com/opendilab/DI-engine/blob/main/ding/policy/ppo.py) and [model](https://github.com/opendilab/DI-engine/blob/main/ding/model/template/vac.py) code. Specifically, the key part of HPPO policy is [here](https://github.com/opendilab/DI-engine/blob/63861b9357bb14f399f1df64f5d0b04a79d84dc9/ding/policy/ppo.py#L220), the key part of HPPO model is[ here](https://github.com/opendilab/DI-engine/blob/63861b9357bb14f399f1df64f5d0b04a79d84dc9/ding/model/template/vac.py#L152).
> 
> Hope this answers your doubts.

Thank you for your reply . I will check it. However, the library is totally different from stable baseline 3, right? Do I have to customize my open ai gym platform as per the standards of di-engine ? Because, i have been getting a lot of errors when I try to utilize an algorithm form di-engine in order to train an agent in my customized open ai gym platform

**Comment by PaParaZz1** [comment]
If you want to transfer your own gym-style env to DI-engine's format, we provide the following tools to help you finish it easily:
- `DingEnvWrapper`, which can transform gym-style env to DI-engine's format direcely, here is a naive demo:
  ```python
  import gym
  from ding.envs import DingEnvWrapper
  cartpole_env = DingEnvWrapper(gym.make('CartPole-v0'))
  pendulum_env = DingEnvWrapper(gym.make('Pendulum-v0'), cfg={'act_scale': True})
  ```
  [Here](https://github.com/opendilab/DI-engine/blob/main/ding/envs/env/ding_env_wrapper.py) is the code implementation link of `DingEnvWrapper`.
- If there are still some problems after using `DingEnvWrapper`, you can refer to this [doc](https://di-engine-docs.readthedocs.io/en/latest/04_best_practice/ding_env.html) to transfer your env manually.
