### ISSUE TITLE
请问，有计划实现CollaQ with Attn吗？

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#440]
-  I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    +  new feature request
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```
如题，看起来CollaQ with Attn不错，既然CollaQ实现了，CollaQ with Attn应该容易吧。

**Comment by PaParaZz1** [comment]
目前实现的CollaQ版本，就是已经包含 with attn 和 without attn 两种设置的，通过改变这个参数即可切换（[link](https://github.com/opendilab/DI-engine/blob/main/ding/model/template/qmix.py#L373)）

**Comment by jaried** [comment]
谢谢您的回答。
