### ISSUE TITLE
AssertionError: gym_hybrid

### ISSUE THREAD

**Issue by ddharshan** [opendilab/DI-engine#442]
Hi
I am new to DI-engine. when I run [DI-engine](https://github.com/opendilab/DI-engine)/[dizoo](https://github.com/opendilab/DI-engine/tree/main/dizoo)/[gym_hybrid](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid)/[envs](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid/envs)/gym_hybrid_env.py  (gym_hybrid_env.py ) code only in jupyter notebook, i am getting the **AssertionError: gym_hybrid** error. can anyone please help me on how to get rid from this??
The documents are required to understand the DI-Engine.

**Comment by PaParaZz1** [comment]
Can you provide more details, like screen snapshots of your errors?

**Comment by ddharshan** [comment]
> Can you provide more details, like screen snapshots of your errors?
Thank you for your reply. Sure, I run this code { [DI-engine](https://github.com/opendilab/DI-engine)/[dizoo](https://github.com/opendilab/DI-engine/tree/main/dizoo)/[gym_hybrid](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid)/[envs](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid/envs)/gym_hybrid_env.py} in jupyter notebook but i got the following error message 
![image](https://user-images.githubusercontent.com/108181384/184530854-e4526399-4ec7-4e46-b210-0f6339288fca.png)

**Comment by PaParaZz1** [comment]
This error could be a repeat register error, which is caused by the repeat import of `GymHybridEnv`.

For simplicity, you can modify line 14 like `@ENV_REGISTRY.register('gym_hybrid', force_overwrite=True)` to figure it out.

**Comment by ddharshan** [comment]
> This error could be a repeat register error, which is caused by the repeat import of `GymHybridEnv`.
> 
> For simplicity, you can modify line 14 like `@ENV_REGISTRY.register('gym_hybrid', force_overwrite=True)` to figure it out.

Yes it worked. Thank you

**Comment by ddharshan** [comment]
Why this error occurs? Is that because of  python 3??
![image](https://user-images.githubusercontent.com/108181384/184545105-eb2c83de-5573-42cb-b227-03cc627545c4.png)

**Comment by ddharshan** [comment]
Also please let me know, why am i getting this error when i run the [DI-engine](https://github.com/opendilab/DI-engine)/[dizoo](https://github.com/opendilab/DI-engine/tree/main/dizoo)/[gym_hybrid](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid)/[entry](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid/entry)/gym_hybrid_ddpg_eval.py code ??

![image](https://user-images.githubusercontent.com/108181384/184545913-448deba4-d37d-4b25-b087-0e8db872c4c3.png)

**Comment by ddharshan** [comment]
Also please let me know, why am i getting this error when i run the [DI-engine](https://github.com/opendilab/DI-engine)/[dizoo](https://github.com/opendilab/DI-engine/tree/main/dizoo)/[gym_hybrid](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid)/[entry](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid/entry)/gym_hybrid_ddpg_main.py code??
![image](https://user-images.githubusercontent.com/108181384/184572903-3ea9fac1-252a-464c-a9ad-2da4645af54a.png)

**Comment by PaParaZz1** [comment]
> Also please let me know, why am i getting this error when i run the [DI-engine](https://github.com/opendilab/DI-engine)/[dizoo](https://github.com/opendilab/DI-engine/tree/main/dizoo)/[gym_hybrid](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid)/[entry](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid/entry)/gym_hybrid_ddpg_main.py code?? ![image](https://user-images.githubusercontent.com/108181384/184572903-3ea9fac1-252a-464c-a9ad-2da4645af54a.png)

For this problem, you should add `replay_path` field in your config, just like
```python
gym_hybrid_hppo_config = dict(
  env=dict(
      replay_path="your own file directory path to save replay video"
  ),
  ...,
)
```

**Comment by PaParaZz1** [comment]
For more detailed discussion, you can join our slack channel and some message to us.

**Comment by ddharshan** [comment]
> For more detailed discussion, you can join our slack channel and some message to us.

[DI-engine](https://github.com/opendilab/DI-engine)/[dizoo](https://github.com/opendilab/DI-engine/tree/main/dizoo)/[gym_hybrid](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid)/[config](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid/config)/gym_hybrid_ddpg_config.py

![image](https://user-images.githubusercontent.com/108181384/184577264-e5e722df-5841-4644-992b-76228753485c.png)
