### ISSUE TITLE
请问SAC支持PER吗？

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#444]
-  I have marked all applicable categories:
    +  new feature request
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  v0.4.1 1.11.0+cu113 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] win32
  ```
如题，因为我的奖励是稀疏奖励，请问DI 的 SAC支持PER吗？是基于TD error计算的吗？

**Comment by PaParaZz1** [comment]
SAC默认是实现了PER的，控制[这里](https://github.com/opendilab/DI-engine/blob/main/ding/policy/sac.py#L82)的两个选项即可，具体priority的更新是基于TD-error，参考[这里](https://github.com/opendilab/DI-engine/blob/main/ding/policy/sac.py#L375)

**Comment by jaried** [comment]
谢谢您的回答。
