### ISSUE TITLE
gym_hybrid: replay_path

### ISSUE THREAD

**Issue by ddharshan** [opendilab/DI-engine#446]
Can you remove the hastag in front of replay_path='gym_hybrid_ddpg_seed0/video' at [DI-engine](https://github.com/opendilab/DI-engine)/[dizoo](https://github.com/opendilab/DI-engine/tree/main/dizoo)/[gym_hybrid](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid)/[config](https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_hybrid/config)/gym_hybrid_ddpg_config.py, ? 
![image](https://user-images.githubusercontent.com/108181384/184834061-a2873f87-c63a-4a19-baa9-e16998fa460c.png)

**Comment by PaParaZz1** [comment]
It is not a necessary field so we just comment it in default config. You can choose whether to enable it according to your demand.
