### ISSUE TITLE
请问，有没有MASAC用于连续MARL环境的demo？

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#456]
- I have marked all applicable categories:

    +  new feature request
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.1 1.12.1+cu116 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] win32
  ```
如题，我用sac用的最多，有没有MASAC用于连续MARL环境的demo？最好能支持增加减少agent。谢谢

**Comment by PaParaZz1** [comment]
可以参考multi-agent mujoco的demo，代码链接在[这里](https://github.com/opendilab/DI-engine/blob/main/dizoo/multiagent_mujoco/config/ant_masac_config.py)。

`增加减少agent`是指什么呢，是指训练过程中动态增加和减少？

**Comment by jaried** [comment]
是的，动态增加和减少agent。

**Comment by PaParaZz1** [comment]
动态增减是个挺麻烦的事情，可以一起讨论下。

在训练过程中减少agent比较好做，只需要一开始预设好最大的local state和global state维度，如果减少，通过state mask/action mask等方式来处理相关信息，让神经网络能够感知到即可。由于大部分multi-agent coopreation算法都是共享local agent network，所以影响不大。

但是在训练过程中增加agent就是比较麻烦的事情了，可能需要结合具体问题来设计下。

**Comment by jaried** [comment]
既然动态增加agent不好做，那我一开始就尽可能考虑多的agent数量，只减少，不增加。请问，有这方面的demo吗？
