### ISSUE TITLE
请问，有没有MAPPO用于连续MARL环境的demo？

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#460]
-  I have marked all applicable categories:
    +  documentation request
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.1 1.12.1+cu116 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] win32
  ```
MAPPO作为SMAC的sota算法，请问有没有连续MARL环境的demo？

**Comment by PaParaZz1** [comment]
我们本周会尝试做一个 MAPPO + MA Mujoco的demo，相关信息会在这个 issue 中保持记录，可以保持关注。

**Comment by PaParaZz1** [comment]
MAPPO + MA Mujoco的demo在 PR #464中，预计今天（9.1）会合并到主分支
