### ISSUE TITLE
CollaQ的问题

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#463]
-  I have marked all applicable categories:
    +  RL algorithm question
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.1 1.12.1+cu116 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] win32
  ```
我在用 [SMAC_3s5z_collaq](https://github.com/opendilab/DI-engine/blob/main/dizoo/smac/config/smac_3s5z_collaq_config.py)学习CollaQ，碰到一些疑惑，想请教您几个问题:

1、CollaQ能否不计算单个agent的rew，只计算总rew？如果不计算单个agent的rew，是不是增加删除agent比较困难？

**Answer:** 第一部分，MADDPG会需要单独的reward，而QMIX一般提供总体的reward，CollaQ是基于QMIX的。第二部分，设置最大agent数即可处理。

2、Obs_alone、independent_obs、special_global_state及else分别代表什么意义？

**Answer:**
https://di-engine-docs.readthedocs.io/zh_CN/latest/13_envs/smac_zh.html

https://github.com/opendilab/DI-engine/blob/69db77e2e54a0fba95d83c9411c6b11cd25beae9/dizoo/smac/config/smac_3s5z_collaq_config.py#L19

https://github.com/opendilab/DI-engine/blob/69db77e2e54a0fba95d83c9411c6b11cd25beae9/dizoo/smac/envs/smac_env.py#L448-L474

3、假如我有两个agent的部分状态是公用的，但是和其他agent不共用，在global_state里面是否写一份就可以了？
**Answer:** 公用的写一份。在每个agent观测到的状态中，会给shared observation留一部分位置。环境可以根据agent id来决定是否给某个agent提供另外某个agent的信息

4、self_feature_range和ally_feature_range是指什么？

https://github.com/opendilab/DI-engine/blob/69db77e2e54a0fba95d83c9411c6b11cd25beae9/dizoo/smac/config/smac_3s5z_collaq_config.py#L34-L35

**Answer:** [:4]是move_feats [4:68]是enemy_feats,[68:124]是ally_feats ,[124:142]是self_feats, [142:150]是agent_id
但是其他环境的好像不太一样，这个环境我就不太理解：

https://github.com/opendilab/DI-engine/blob/17fc41d7f1a69a452f488e282e194a7e46a86237/dizoo/petting_zoo/config/ptz_simple_spread_collaq_config.py#L32-L33

5、update_per_collect指的是多少个collect更新1次梯度吗？那一个collect收集多少step在哪设置？
https://github.com/opendilab/DI-engine/blob/69db77e2e54a0fba95d83c9411c6b11cd25beae9/dizoo/smac/config/smac_3s5z_collaq_config.py#L43

6、batch_size，是网络学习的每次取样数吗？我一般用大的batch_size，如4096，这里设4096有没有问题？
https://github.com/opendilab/DI-engine/blob/69db77e2e54a0fba95d83c9411c6b11cd25beae9/dizoo/smac/config/smac_3s5z_collaq_config.py#L44

7、discount_factor是不是就是gamma，为什么设置为0.95而不是0.99？
https://github.com/opendilab/DI-engine/blob/69db77e2e54a0fba95d83c9411c6b11cd25beae9/dizoo/smac/config/smac_3s5z_collaq_config.py#L49

8、CollaQ有支持PER的计划吗？
https://github.com/opendilab/DI-engine/blob/69db77e2e54a0fba95d83c9411c6b11cd25beae9/ding/policy/collaq.py#L128

**Comment by PaParaZz1** [comment]
Q8：本周我们会支持一下并跑一组实验看看
Q7：就是一般RL中所指的gamma，当时设置0.95应该是在这个环境上调出来比较好的结果，当然你也可以用一些超参数搜索工具调一调看，可以试试我们新开发的 [LightTuner](https://github.com/opendilab/LightTuner)
Q6：这里的batch size是网络一次更新所用的样本数。对于不同RL算法和环境，这个值设置的范围不相同。根据我们的经验，在smac环境上，off-policy算法，32-256是合理的范围。超过这个范围更大的batch size，直接使用可能会出现训练不稳定现象，如果要用大的batch size需要对神经网络的优化比较有经验，可能要在优化器和梯度裁剪上下很多工夫，比如参考 [lamb](https://github.com/cybertronai/pytorch-lamb)
Q5：逻辑是这样，每次收集 n_sample 个样本（每个样本长度为 unroll_len），然后切换到训练，从replay buffer中每次采样batch size个样本，训练 update_per_collect次

**Comment by jaried** [comment]
Q4我弄明白了，[:4]是move_feats [4:68]是enemy_feats,[68:124]是ally_feats ,[124:142]是self_feats, [142:150]是agent_id

**Comment by jaried** [comment]
Q2找到了：

https://di-engine-docs.readthedocs.io/zh_CN/latest/13_envs/smac_zh.html

**Comment by jaried** [comment]
Q4 还有点疑惑。

Q8 等你们发布结果再关闭issue。

**Comment by jaried** [comment]
请问，Q5,如下,那是每次收集32个episode?每个episode中取10个样本？不是这个意思吧？
https://github.com/opendilab/DI-engine/blob/69db77e2e54a0fba95d83c9411c6b11cd25beae9/dizoo/smac/config/smac_3s5z_collaq_config.py#L52-L56

**Comment by PaParaZz1** [comment]
> 请问，Q5,如下,那是每次收集32个episode?每个episode中取10个样本？不是这个意思吧？
> 
> https://github.com/opendilab/DI-engine/blob/69db77e2e54a0fba95d83c9411c6b11cd25beae9/dizoo/smac/config/smac_3s5z_collaq_config.py#L52-L56

每次收集32个episode，比如一个episode是80帧，会按照unroll_len=10来划分样本，即这里一个episode会产生8个样本

**Comment by zerlinwang** [comment]
> Q4 还有点疑惑。 Q6 我明白了，MARL和单agent 的RL不一样，OBS维度很高，所以，batch_size和单agent的RL 的batch_size不能对比。 Q8 等你们发布结果再关闭issue。

Q8 你好，我们添加了PER，稍后会merge相关代码，并在smac的3s5z上测试了是否使用PER的结果，如下所示：
![FUbaDo8mLD](https://user-images.githubusercontent.com/80957609/188600435-08741f69-7626-4385-838c-aaad5f55e997.png)

**Comment by jaried** [comment]
非常感谢
