### ISSUE TITLE
EasyDict的建议

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#466]
-  I have marked all applicable categories:
    +  code design/refactor
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.1 1.12.1+cu116 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] win32
  ```
EasyDict有很多的属性Warning，建议修改

![1662090008734](https://user-images.githubusercontent.com/26672425/188054582-937086d9-4979-4403-bf8c-86a52d75a13b.png)

**Comment by HansBug** [comment]
您好，这个easydict是来自于开源的轮子，源代码在此：https://github.com/makinacorpus/easydict/blob/master/easydict/__init__.py#L1

我们目前使用的就是这个，如果后续有必要的话，可以考虑将该部分代码进行移植，不过得考虑开源协议的问题。

**Comment by jaried** [comment]
直接继承Namespace好像有点问题，       
`super(EasyDict, self).__setitem__(name, value)`用的是dict的方法。
开源的问题那是得考虑，Warning比较多也得考虑。
本建议仅供参考。

**Comment by jaried** [comment]
应该不用移植，就是在声明功能的参数类型的时候，声明为EasyDict类型就没有warning了。
比如：
```python
def serial_pipeline(
        input_cfg: Union[str, Tuple[EasyDict, EasyDict]],
        seed: int = 0,
        env_setting: Optional[List[Any]] = None,
        model: Optional[torch.nn.Module] = None,
        max_train_iter: Optional[int] = int(1e10),
        max_env_step: Optional[int] = int(1e10),
) -> 'Policy':
```

**Comment by jaried** [comment]
DotDict没有license，如果在功能参数声明类型时，声明为DotDict，不会像EasyDict那样有warning，仅供参考：

https://mws.readthedocs.io/en/develop/reference/DotDict.html

**Comment by jaried** [comment]
另外，自己刚写了个类，但是只能当类实例用，dict转换为类实例也很方便，没有warning，供参考：

```python
from argparse import Namespace


class MyDict(Namespace):
    def __init__(self, **kwargs):
        super().__init__()
        if isinstance(kwargs, dict):
            for k, v in kwargs.items():
                if not isinstance(v, dict):
                    setattr(self, k, v)
                else:
                    setattr(self, k, self.__class__(**v))

```
