### ISSUE TITLE
DI有没有用wandb的demo?

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#468]
-  I have marked all applicable categories:
    +  new feature request
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.1 1.12.1+cu116 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] win32
  ```

如题，想用wandb替换tensorboard。

**Comment by PaParaZz1** [comment]
我们上周开始正在添加wandb相关的模块，将会在下下个版本适配整合完毕（v0.5.0，包含wandb的常用功能以及report），目前预计应该是在9.16之前更新

**Comment by jaried** [comment]
可以查看nn的权重分布图表吗？

**Comment by PaParaZz1** [comment]
> 可以查看nn的权重分布图表吗？

这个功能有加，预计本周会有相关PR
