### ISSUE TITLE
建议修改语句DI-engine/ding/config/config.py

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#469]
-  I have marked all applicable categories:
    +  exception-raising bug
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.1 1.12.1+cu116 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] win32
  ```
因为我把`cfg.exp_name`改成带文件夹的，所以在创建文件夹时出错，下面语句建议改成：
```python
os.makedirs(cfg.exp_name)
```
https://github.com/opendilab/DI-engine/blob/89c0ea3a6f5fe174e1491816f8f61521e0b641da/ding/config/config.py#L464

**Comment by PaParaZz1** [comment]
好的谢谢建议，我会尽快修改下

**Comment by PaParaZz1** [comment]
已修改 https://github.com/opendilab/DI-engine/commit/dbe435051428b8ab6ef24dbc4cad8175e18e6640
