### ISSUE TITLE
CollaQ不能修改激活函数

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#470]
-  I have marked all applicable categories:
    +  RL algorithm bug
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.1 1.12.1+cu116 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] win32
  ```
`CollaQ` 继承的是`Policy`，均没有设置激活函数的参数入口。

https://github.com/opendilab/DI-engine/blob/89c0ea3a6f5fe174e1491816f8f61521e0b641da/ding/policy/collaq.py#L15

https://github.com/opendilab/DI-engine/blob/89c0ea3a6f5fe174e1491816f8f61521e0b641da/ding/policy/base_policy.py#L13

**Comment by PaParaZz1** [comment]
我将会打开CollaQ相关model的激活函数设置开关，目前这里确实是写死了 https://github.com/opendilab/DI-engine/blob/main/ding/model/template/qmix.py#L403

**Comment by PaParaZz1** [comment]
已处理 https://github.com/opendilab/DI-engine/commit/24f60fe2e3274c55bd243429b1ee82b2fc88901b

**Comment by jaried** [comment]
非常感谢！

**Comment by PaParaZz1** [comment]
已更新 https://github.com/opendilab/DI-engine/commit/a5f51503ba6462d6e953e640707ecc5a728133de
