### ISSUE TITLE
MASAC的两个问题

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#478]
-  I have marked all applicable categories:
    +  new feature request
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.1 1.12.1+cu116 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] linux
  ```

Q1:ant_masac_config中，只有agent_state和global_state，如果有一个agent失效，是否把对应的agent_state和global_state全部置为0即可？
Q2:masac的隐藏层网络使用的是单层网络，如果我要使用3层网络比如[512,512,512]，我该如何修改？

Q2找到了，actor_head_layer_num=3和critic_head_layer_num=3即可。但是`如何设置`不同宽度的网络呢？比如[512,256,128]?

https://github.com/opendilab/DI-engine/blob/ac9f33c577e873b89bcc1e5ed953e0c58f463b34/dizoo/multiagent_mujoco/config/ant_masac_config.py#L26-L27

**Comment by PaParaZz1** [comment]
Q1：如果有一个agent失效，应该把其相应的**大部分**state进行某种失效mask（可以是置0，但得保证0只能表达失效这一种语义，如果会和其他特征语义冲突，建议换个其他值），但值得注意的是，这个agent的agent id对应的特征应该保留，表明这部分是这个id对应的agent失效了。

Q2：你找到的参数是正确的，一般情况下，在提取到特征向量（即深层特征）之后，后续的head不太需要网络宽度的变化。如果你要进一步修改的话，其实建议是自己参照`ding/model/template`里面的模型自定义一个拥有类似接口的模型，可以参考这个[例子](https://github.com/opendilab/DI-engine/blob/main/dizoo/box2d/bipedalwalker/config/bipedalwalker_ppopg_config.py#L55)。

**Comment by jaried** [comment]
谢谢您的回答
