### ISSUE TITLE
Meaning of batch_size in config files

### ISSUE THREAD

**Issue by cpwan** [opendilab/DI-engine#480]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [x] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```
 v0.4.2 1.10.0+cu102 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) 
 [GCC 7.3.0] linux
```
---
Hi there, I am running the [cartpole_a2c](https://github.com/opendilab/DI-engine/blob/9e2dee3681f7b61e3800680f8d4b77ad1358c8f0/dizoo/classic_control/cartpole/config/cartpole_a2c_config.py#L20) example. 
I am trying to understand how things work in DI-engine. 
I found it weird that the `batch_size` seems to have no effect on the training.
```python
cartpole_a2c_config['policy']['learn']['batch_size']
```
Even I changed the batch_size from `64` to `'apple'`. I can still get the training running with the `python dizoo/classic_control/cartpole/config/cartpole_a2c_config.py` command.
```diff
-            batch_size=64,
+            batch_size='apple',
```

I suspect that the `batch_size` is not even used in the training pipeline.
When I printed out the size of `data` in `A2CPolicy._forward_learn(data)` [here](https://github.com/opendilab/DI-engine/blob/9e2dee3681f7b61e3800680f8d4b77ad1358c8f0/ding/policy/a2c.py#L95), I found that the first dimension of the tensors corresponds to `cartpole_a2c_config['policy']['collect']['n_sample']` instead.

What is the purpose fo the `cartpole_a2c_config['policy']['learn']['batch_size']`?

**Comment by PaParaZz1** [comment]
It is indeed a bug due to version updates, for other algorithm like PPO, `n_sample` data will batch split into some batch with size of `batch_size` ([implementation](https://github.com/opendilab/DI-engine/blob/main/ding/policy/ppo.py#L198)), I'll add this operation in A2CPolicy and test its performance.

**Comment by PaParaZz1** [comment]
I have fixed this bug and test its perfromance on lunarlander, you can adjust related hyper-parameter accordint to you own propose.
<img width="729" alt="Screen Shot 2022-09-15 at 7 16 43 PM" src="https://user-images.githubusercontent.com/33195032/190391271-cb97bd3e-670a-4578-9041-97cbbb5de500.png">
