### ISSUE TITLE
Type conversion in ding_env_wrapper

### ISSUE THREAD

**Issue by cpwan** [opendilab/DI-engine#482]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [x] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```
---
Related code: 
https://github.com/opendilab/DI-engine/blob/main/ding/envs/env/ding_env_wrapper.py

Problem:
The implementation does the type conversion with `to_ndarray(obs).astype(np.float32)`  like [here](https://github.com/opendilab/DI-engine/blob/fbe02b453b4ef78ee678bacc4bfa7d5d1874501c/ding/envs/env/ding_env_wrapper.py#L71). It assumes `np.ndarray` to be the output of `to_ndarray`. However, for nested observation, the `to_ndarray` can take in a dict and return a dict. It should be better to replace it with `to_ndarray(obs, np.float32)`.

I can do a PR to fix it.

**Comment by PaParaZz1** [comment]
Thank you for contributing our repo. Your modification is more reasonble for nested data. I'll merge #483 when CI pass.
