### ISSUE TITLE
能否实现maac及连续maac？

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#487]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [x] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```
maac是离散动作，能否实现maac及连续动作的maac?

论文地址：
https://arxiv.org/pdf/1810.02912.pdf

**Comment by PaParaZz1** [comment]
这篇论文效果其实不太行，他的实验环境也都过于简单。目前的QMIX/MAPPO/MASAC肯定强于这个
