### ISSUE TITLE
di-engine有envpool的demo吗？

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#498]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.12.1+cu116 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
如题，di-engine有envpool的demo吗？

**Comment by PaParaZz1** [comment]
以前做过一个，可以参考这个[示例](https://github.com/opendilab/DI-engine/blob/main/dizoo/atari/entry/pong_dqn_envpool_main.py)，你可以先试试看

**Comment by jaried** [comment]
谢谢！
