### ISSUE TITLE
Process finished with exit code -1073741571 (0xC00000FD)

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#502]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.12.1+cu116 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
masac算法，使用serial_pipeline，执行到下面语句的时候报错，没有其他提示，请问如何解决？

https://github.com/opendilab/DI-engine/blob/c7bbe1aab18ae20394c3a6718074ae0ce0454719/ding/entry/serial_entry.py#L78

debug到下面语句：
https://github.com/opendilab/DI-engine/blob/c7bbe1aab18ae20394c3a6718074ae0ce0454719/ding/worker/replay_buffer/naive_buffer.py#L80-L82
```python
Process finished with exit code -1073741571 (0xC00000FD)
```

**Comment by PaParaZz1** [comment]
每次运行都会稳定复现这个问题吗？这个monitor只是内部开了一个监控线程而已

**Comment by jaried** [comment]
是的，每次都出现

**Comment by PaParaZz1** [comment]
> 是的，每次都出现

你先尝试注释掉naive_buffer.py里所有和periodic_thruput_monitor相关的代码试试？另外，有更多的报错信息吗，这个信息看不出来是啥原因。。。

**Comment by jaried** [comment]
和periodic_thruput_monitor相关的代码全部注释掉后，可以正常运行，没有其他报错信息

**Comment by PaParaZz1** [comment]
好的，你可以提供一个单独的出现这个报错的代码分支吗，我们在我们这边的测试机器上查一下这个问题的根本原因

**Comment by jaried** [comment]
代码见：
https://github.com/jaried/study_di

**Comment by zjowowen** [comment]
Hi, jaried!

My environment is "v0.4.3 1.12.1+cpu 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] win32".

No error was found during create buffer. (Minor changes to your repository, "securities_multi.py" Line 76.)

Perhaps you could use breakpoint to make a step by step debug in the process of buffer to find more information about it.
If you use vscode, you could just turn off the ""justMyCode": false" in file "launch.json".

**Comment by jaried** [comment]
我再看看，谢谢！
