### ISSUE TITLE
为什么collector_env和evaluator_env的pid相同

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#510]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
import ding, torch, sys
print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.12.1+cu116 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
我用serial_pipeline生成的环境，为什么collector_env和evaluator_env的pid相同？
代码和上一个issue的代码一样：
https://github.com/jaried/study_di
```
2022-10-10 23:26:52 - PID: 14576
2022-10-10 23:27:14 - PID: 14576
```

**Comment by PaParaZz1** [comment]
你这里的[配置](https://github.com/jaried/study_di/blob/main/option_masac_config.py#L90)使用的是`base`，换成`subprocess`就是多个进程了。一般来说，base是伪的多进程，用来调试代码；调通没问题之后，就用`subprocess`来实际运行。

**Comment by jaried** [comment]
我改成    `env_manager=dict(type='subprocess'),`
仍然是同一个进程
```python
2022-10-11 14:42:07 - PID: 16296
2022-10-11 14:44:56 - PID: 16296
```

**Comment by PaParaZz1** [comment]
我在我本机运行了你提供的代码（改了一小点代码，不过不影响结论），我这边用subprocess是能跑的，而且PID也不同，如下图所示：

<img width="1386" alt="Screen Shot 2022-10-13 at 12 48 39 PM" src="https://user-images.githubusercontent.com/33195032/195504295-4b33d155-75f7-4e9d-9fb7-26bb3d491551.png">

我的环境是：
```python
import ding, torch, sys
print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.8.0 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] darwin
```

所以看起来可能是windows相关的问题，你是只有这一种系统环境吗？

**Comment by jaried** [comment]
我的ubuntu cuda有点问题，用cpu模式运行了一下，还是同样的pid

```python
import ding, torch, sys
print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.12.1+cu116 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] linux
```
![image](https://user-images.githubusercontent.com/26672425/195529010-c55905da-e029-4b74-b3da-74e748c01737.png)

**Comment by PaParaZz1** [comment]
我这边在 centos 服务器上运行了一下，也是没问题的。。。运行截图如下：

<img width="965" alt="Screen Shot 2022-10-19 at 6 07 41 PM" src="https://user-images.githubusercontent.com/33195032/196662592-bc5b9453-e69e-4c85-bb5b-e7cfd1fd5c0d.png">
相关库版本信息是：
```python
>>> import ding, torch, sys
>>> print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.10.0+cu102 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] linux
```

难道是运行代码有些地方不一致？我把我实际跑的你的仓库代码放到[这里](https://github.com/PaParaZz1/study_di)了，你可以运行下看看，直接`python3 -u option_masac_config.py`

**Comment by jaried** [comment]
我用您的代码运行了一下，是正常的。

但是我比较代码没发现哪不同。我自己再找找原因吧。谢谢您的回答。
