### ISSUE TITLE
How to evaluate & render?

### ISSUE THREAD

**Issue by WaterHyacinthInNANHU** [opendilab/DI-engine#515]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```

  ```
  v0.4.3 1.12.1+cu113 3.7.13 (default, Mar 29 2022, 02:18:16) 
  [GCC 7.5.0] linux
  ```

1. How to evaluate the trained networks? 
2. Is rendering supported? For instance, to save a gif while evaluating in MPE.

**Comment by PaParaZz1** [comment]
For evaluating the trained networks, you can refer to this [discussion](https://github.com/opendilab/DI-engine/discussions/508), we prepare `eval` and `deploy` examples.

**Comment by PaParaZz1** [comment]
For rendering, you can implement and call the `enable_save_replay` method to save replay video, like this [demo](https://github.com/opendilab/DI-engine/blob/main/dizoo/classic_control/cartpole/entry/cartpole_dqn_eval.py#L40), related code can also be found [here](https://github.com/opendilab/DI-engine/blob/main/ding/envs/env/ding_env_wrapper.py#L55).
