### ISSUE TITLE
为什么No module named 'ditk'

### ISSUE THREAD

**Issue by zxnuli** [opendilab/DI-engine#520]
ERROR: Could not find a version that satisfies the requirement ditk (from versions: none)
ERROR: No matching distribution found for ditk

**Comment by zxnuli** [comment]
网上的解决方法是输入：
pip install ditk -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
但是仍然显示：
ERROR: Could not find a version that satisfies the requirement ditk (from versions: none)
ERROR: No matching distribution found for ditk
设备：M1 mac

**Comment by PaParaZz1** [comment]
DI-engine的依赖库列表里有这个（[代码链接](https://github.com/opendilab/DI-engine/blob/main/setup.py#L82)），为什么你安装的时候没安装这个库呢，有点奇怪。

不过要解决的话也很简单，`pip install DI-toolkit` 即可。

**Comment by zxnuli** [comment]
已经解决！感谢帮助🙏
