### ISSUE TITLE
如何存储和读取replay buffer为h5文件

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#529]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.12.1+cu116 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
请问：
1、缓存如何存为h5，并且如何读缓存
2、需要定期存缓存时，缓存如果过大，如何切割存为h5，并且如何读缓存

**Comment by PaParaZz1** [comment]
你这是要缓存的数据是指，是 replay buffer 里的数据吗，具体有多大

**Comment by jaried** [comment]
是的，

**Comment by jaried** [comment]
是的，大概12M条，obs大小大概如下：
```python
        self._observation_space = _observation_space = gym.spaces.Dict(
            {
                'agent_state': gym.spaces.Box(
                    low=-1, high=1, shape=(4,336), dtype=np.float32
                ),
                'global_state': gym.spaces.Box(
                    low=-1, high=1, shape=(4, 994), dtype=np.float32
                )
            }
        )
```

**Comment by PaParaZz1** [comment]
- 首先第一点，你这个环境的state数据可以适当压缩吗，比如可以用uint8表示的其实没必要用float32。如果这个可以在环境里修改，那么存储在replay buffer中的数据就可以大概缩小为原来的四分之一
- 然后对于replay buffer内部，我理解这个功能需求，相当于是将replay buffer里的数据通过某种方式，自动转换成h5放到磁盘里，如果读到这部分数据，再去h5里面读一下，从而减少对内存的占用是吗？

**Comment by jaried** [comment]
> * 首先第一点，你这个环境的state数据可以适当压缩吗，比如可以用uint8表示的其实没必要用float32。如果这个可以在环境里修改，那么存储在replay buffer中的数据就可以大概缩小为原来的四分之一
目前我用的是sac算法，需要做obs缩放，所以obs用的是-1到1的区间。
> * 然后对于replay buffer内部，我理解这个功能需求，相当于是将replay buffer里的数据通过某种方式，自动转换成h5放到磁盘里，如果读到这部分数据，再去h5里面读一下，从而减少对内存的占用是吗？
replay buffer我是这么用的，1、因为我的env使用了大量数据，数据的质量不一定可控，而且我的env可能会出现bug，为了避免训练时出现异常，定期存replay buffer可以继续训练。2、第二次训练时，网络权重从0开始，并且读上次训练出好的模型的replay buffer，可以提高成绩。

**Comment by PaParaZz1** [comment]
明白了，所以其实你的需求更简单，只需要自动定期存储replay buffer中的数据，且能够在重新训练的时候加载进来就可以了对吧

**Comment by jaried** [comment]
是的，很简单。只要能把replay buffer分文件保存和读取就行了。

**Comment by PaParaZz1** [comment]
相关功能已在 #542 中实现
