### ISSUE TITLE
请问，如何给训练env和测试env某个值赋不同的值？

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#530]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.12.1+cu116 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
我需要把训练的env.train设为True，测试的env.train设为False
我使用如下两种方法修改serial_entry.py，都未能成功，请问该如何设置？
```python
    cfg.env.manager.train = True
    collector_env = create_env_manager(cfg.env.manager, [partial(env_fn, cfg=c) for c in collector_env_cfg])
    cfg.env.manager.train = False
    evaluator_env = create_env_manager(cfg.env.manager, [partial(env_fn, cfg=c) for c in evaluator_env_cfg])
```
```python
    collector_env_cfg[0].train = True
    collector_env = create_env_manager(cfg.env.manager, [partial(env_fn, cfg=c) for c in collector_env_cfg])
    evaluator_env_cfg[0].train = False
    evaluator_env = create_env_manager(cfg.env.manager, [partial(env_fn, cfg=c) for c in evaluator_env_cfg])
    
```

**Comment by PaParaZz1** [comment]
你这样两次修改的是同一个对象，所以不会生效。
比较暴力的解决方式是各自deepcopy一份cfg然后再赋值，传给不同的env manager。
如果你是继承DI-engine的BaseEnv派生你的环境子类的话，推荐像Atari一样重写这两个方法：[传送门](https://github.com/opendilab/DI-engine/blob/main/dizoo/atari/envs/atari_env.py#L105)

**Comment by jaried** [comment]
谢谢您的回答！我得考虑一下怎么写，因为我同时还需要用一个dict做share_memory。

**Comment by jaried** [comment]
请问，如果我只需要把`is_train`属性改成不一样的，不用deepcopy如何解决？

**Comment by PaParaZz1** [comment]
deepcopy还是得有呀，你得保证`collect`和`eval`的使用的`cfg`不一样，否则你的赋值修改是没意义的，后面的改动会覆盖前面的

**Comment by jaried** [comment]
那，我如果同时想把`share_memory:dict`给`collect`及`eval`同时使用，我该如何设置呢？

**Comment by PaParaZz1** [comment]
在入口文件里，deepcopy配置文件后，手动操作下，准备两份env manager的config传给EnvManager

**Comment by jaried** [comment]
明白了，谢谢。
