### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#531]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.12.1+cu116 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
出错提示如下：
```python
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\ding\worker\learner\base_learner.py", line 165, in wrapper
    ret = fn(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\ding\worker\learner\base_learner.py", line 205, in train
    log_vars = self._policy.forward(data, **policy_kwargs)
  File "D:\Anaconda3\lib\site-packages\ding\policy\sac.py", line 843, in _forward_learn
    loss_dict['critic_loss'], td_error_per_sample0 = v_1step_td_error(q_data0, self._gamma)
  File "D:\Anaconda3\lib\site-packages\ding\rl_utils\td.py", line 320, in v_1step_td_error
    if len(v.shape) == len(reward.shape):
AttributeError: 'list' object has no attribute 'shape'
```
reward的值为：
```python
reward[0].shape
Out[4]: torch.Size([4096])

reward
Out[5]: 
[tensor([ 0.0170, -0.0027, -0.0095,  ...,  0.0099, -0.0055, -0.0047],
        device='cuda:0')]
```

**Comment by PaParaZz1** [comment]
你的reward为什么还被list包了一层呢，检查下从环境返回的reward是不是标准格式吧，应该为np数组，且维度为(1, )

**Comment by jaried** [comment]
找到了，我的rew转换为np.array执行了两次：
```python
        rew = to_ndarray([rew])
```
