### ISSUE TITLE
ModuleNotFoundError: No module named 'ding'

### ISSUE THREAD

**Issue by liuqi8827** [opendilab/DI-engine#535]
Hi,
 
I installed DI-engine succesfully.

However, when I run:
1. `cd /home/xx/DI-engine/dizoo/classic_control/pendulum/entry`
2. `python3 -u pendulum_d4pg_main.py`
 I got the error:
Traceback (most recent call last):
  File "pendulum_d4pg_main.py", line 5, in <module>
    from ding.config import compile_config
ModuleNotFoundError: No module named 'ding'

Can you give me some suggestions?

**Comment by liuqi8827** [comment]
I can run `python3 -u pendulum_d4pg_main.py` succesfully.
However:
1. `cd /home/lq/DI-engine/dizoo/mujoco/entry`
2. `python3 -u mujoco_d4pg_main.py`

I got the error:
```
Traceback (most recent call last):
  File "mujoco_d4pg_main.py", line 67, in <module>
    main(hopper_d4pg_config)
  File "mujoco_d4pg_main.py", line 31, in main
    env_fn=[lambda: MujocoEnv(cfg.env) for _ in range(collector_env_num)], cfg=cfg.env.manager
  File "/home/lq/DI-engine/ding/envs/env_manager/base_env_manager.py", line 109, in __init__
    self._env_ref = self._env_fn[0]()
  File "mujoco_d4pg_main.py", line 31, in <lambda>
    env_fn=[lambda: MujocoEnv(cfg.env) for _ in range(collector_env_num)], cfg=cfg.env.manager
  File "/home/lq/DI-engine/dizoo/mujoco/envs/mujoco_env.py", line 36, in __init__
    self._action_clip = cfg.action_clip
AttributeError: 'EasyDict' object has no attribute 'action_clip'
```

Can you give me some suggestions?

**Comment by PaParaZz1** [comment]
It is the compatibility bug about version updates. You can add corresponding config field in `hopper_d4pg_config.py` to solve this problem as follows:
```python
env = dict(
  ...,
  action_clip=False,
  ...,
)
```

**Comment by norman26625** [comment]
btw,' a' asd

**Comment by norman26625** [comment]
btw, you may encounter the same problem in   `delay_reward_step`   `replay_path`    `save_replay_gif`    `replay_path_gif`, you can also solve these problem form @PaParaZz1  comment

**Comment by liuqi8827** [comment]
It runs successfully.
Thanks a lot!

**Comment by chuaning** [comment]
Hello,
 I want to ask that when something runs like this:
![image](https://github.com/opendilab/DI-engine/assets/100500234/6ddc1bb7-eb72-4fd7-a9de-6c2088470d38)
is it the same reason and the same answer?

**Comment by PaParaZz1** [comment]
> Hello, I want to ask that when something runs like this: ![image](https://private-user-images.githubusercontent.com/100500234/299599174-6ddc1bb7-eb72-4fd7-a9de-6c2088470d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTE1NzYsIm5iZiI6MTcwNjE5MTI3NiwicGF0aCI6Ii8xMDA1MDAyMzQvMjk5NTk5MTc0LTZkZGMxYmI3LWViNzItNGZkNy1hOWRlLTZjMjA4ODQ3MGQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxNDAxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmE2ZTQ3ZTZmNTg1YjcwZDA1MDgzZTNiNTBlNTc2ZTJlNGFlYmQ4ZDQ4N2Y1NjgzNzBmYzdkZWFiOTYyMmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PTrJHYoA_1HQ_8ewLJdFyoB9eIZ64kcEpdusvlNGm3A) is it the same reason and the same answer?

Maybe not. How do you install DI-engine? You can provide more details and we will offer further support.

**Comment by chuaning** [comment]
> > Hello, I want to ask that when something runs like this: ![image](https://private-user-images.githubusercontent.com/100500234/299599174-6ddc1bb7-eb72-4fd7-a9de-6c2088470d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTE1NzYsIm5iZiI6MTcwNjE5MTI3NiwicGF0aCI6Ii8xMDA1MDAyMzQvMjk5NTk5MTc0LTZkZGMxYmI3LWViNzItNGZkNy1hOWRlLTZjMjA4ODQ3MGQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxNDAxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmE2ZTQ3ZTZmNTg1YjcwZDA1MDgzZTNiNTBlNTc2ZTJlNGFlYmQ4ZDQ4N2Y1NjgzNzBmYzdkZWFiOTYyMmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PTrJHYoA_1HQ_8ewLJdFyoB9eIZ64kcEpdusvlNGm3A) is it the same reason and the same answer?
> 
> Maybe not. How do you install DI-engine? You can provide more details and we will offer further support.

是这样的，我在pycharm的终端（conda虚拟环境）用git clone把DI-engine下载到我的默认项目文件夹里，但是运行的时候找不到ding是什么，出现的错误是这样的：
Traceback (most recent call last):
  File "D:\pythonProject\pythonProject1\DI-engine\dizoo\gym_hybrid\config\gym_hybrid_hppo_config.py", line 63, in <module>
    from ding.entry import serial_pipeline_onpolicy
ModuleNotFoundError: No module named 'ding'

**Comment by PaParaZz1** [comment]
> > > Hello, I want to ask that when something runs like this: ![image](https://private-user-images.githubusercontent.com/100500234/299599174-6ddc1bb7-eb72-4fd7-a9de-6c2088470d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTE1NzYsIm5iZiI6MTcwNjE5MTI3NiwicGF0aCI6Ii8xMDA1MDAyMzQvMjk5NTk5MTc0LTZkZGMxYmI3LWViNzItNGZkNy1hOWRlLTZjMjA4ODQ3MGQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxNDAxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmE2ZTQ3ZTZmNTg1YjcwZDA1MDgzZTNiNTBlNTc2ZTJlNGFlYmQ4ZDQ4N2Y1NjgzNzBmYzdkZWFiOTYyMmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PTrJHYoA_1HQ_8ewLJdFyoB9eIZ64kcEpdusvlNGm3A) is it the same reason and the same answer?
> > 
> > 
> > Maybe not. How do you install DI-engine? You can provide more details and we will offer further support.
> 
> 是这样的，我在pycharm的终端（conda虚拟环境）用git clone把DI-engine下载到我的默认项目文件夹里，但是运行的时候找不到ding是什么，出现的错误是这样的： Traceback (most recent call last): File "D:\pythonProject\pythonProject1\DI-engine\dizoo\gym_hybrid\config\gym_hybrid_hppo_config.py", line 63, in from ding.entry import serial_pipeline_onpolicy ModuleNotFoundError: No module named 'ding'

Did you install DI-engine with the command like `cd DI-engine && pip3 install -e .`? If not, you can try this command and describe the way you did before.

**Comment by chuaning** [comment]
Thank you for your advice!
![image](https://github.com/opendilab/DI-engine/assets/100500234/94b8f9b1-8eee-4fe0-9dcd-7c099c0012d8)
I forget whether used it or not, but the command goes well now like the image tells, but the ding still can't be recognized. And my path is as the second image you can see:
![image](https://github.com/opendilab/DI-engine/assets/100500234/ab77637d-37a9-45ad-8fb9-ebca5c8c8d5a)
 Also, the project files look like this:
![image](https://github.com/opendilab/DI-engine/assets/100500234/7fe8d42b-94aa-40fa-ba3d-50588ed2f74e)
Do I need to reload the DI-engine through pip3?
