### ISSUE TITLE
Why the performance of DI-DQN is much worse than that of RLlib under the same hyperparameters?

### ISSUE THREAD

**Issue by mahuangxu** [opendilab/DI-engine#539]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:

I made an env and drave it with DQN provided in DI-engine and RLlib respectively with the same hyperparameters. However, I found that the performance of DI-engine is much worse than that of RLlib. I want to know why and how to further enhance DI so that I can use the imitation learning algorithm that is not available in RLlib. I guess it's because there are some inconsistent super parameters that are not provided. Have you observed this phenomenon and what solutions do you have? Thanks!
[collector_csv_logger.csv](https://github.com/opendilab/DI-engine/files/9977085/collector_csv_logger.csv)

![image](https://user-images.githubusercontent.com/55223128/200994150-05ed3702-7874-4a66-83c6-f5a0f1724c19.png)

### Hyperparameters in RLlib:
```python
{
  "double_q": true,
  "dueling": false,
  "env": "<class 'RLlib_graph_sfc_env_all_path.GraphRoutingEnv'>",
  "exploration_config": {
    "epsilon_timesteps": 10000,
    "final_epsilon": 0.02,
    "initial_epsilon": 1.0,
    "type": "EpsilonGreedy"
  },
  "framework": "torch",
  "gamma": 0.99,
  "hiddens": [],
  "lr": 0.005,
  "model": {
    "custom_model": "graph_routing_model",
    "post_fcnet_activation": "relu",
    "post_fcnet_hiddens": [
      256,
      256
    ]
  },
  "replay_buffer_config": {
    "capacity": 100000
  },
  "rollout_fragment_length": 1024,
  "seed": 0,
  "timesteps_per_iteration": 4096,
  "train_batch_size": 4096
}
```

### Hyperparameters in DI-engine:
```python
exp_config = {
    'env': {
        'manager': {
            'episode_num': float("inf"),
            'max_retry': 1,
            'retry_type': 'reset',
            'auto_reset': True,
            'step_timeout': None,
            'reset_timeout': None,
            'retry_waiting_time': 0.1,
            'cfg_type': 'BaseEnvManagerDict'
        },
        'collector_env_num': 1,
        'evaluator_env_num': 1,
        'n_evaluator_episode': 1,
        'stop_value': 5000
    },
    'policy': {
        'model': {
            'dueling': False
        },
        'learn': {
            'learner': {
                'train_iterations': 10000,
                'dataloader': {
                    'num_workers': 0
                },
                'log_policy': True,
                'hook': {
                    'load_ckpt_before_run': '',
                    'log_show_after_iter': 20,
                    'save_ckpt_after_iter': 20,
                    'save_ckpt_after_run': True
                },
                'cfg_type': 'BaseLearnerDict'
            },
            'multi_gpu': False,
            'update_per_collect': 3,
            'batch_size': 4096,
            'learning_rate': 0.005,
            'target_update_freq': 256,
            'ignore_done': False
        },
        'collect': {
            'collector': {
                'deepcopy_obs': False,
                'transform_obs': False,
                'collect_print_freq': 20,
                'cfg_type': 'SampleSerialCollectorDict'
            },
            'unroll_len': 1,
            'n_sample': 1024
        },
        'eval': {
            'evaluator': {
                'eval_freq': 1000,
                'cfg_type': 'InteractionSerialEvaluatorDict',
                'n_episode': 1,
                'stop_value': 5000
            }
        },

        'other': {
            'replay_buffer': {
                'type': 'advanced',
                'replay_buffer_size': 100000,
                'max_use': float("inf"),
                'max_staleness': float("inf"),
                'alpha': 0.6,
                'beta': 0.4,
                'anneal_step': 100000,
                'enable_track_used_data': False,
                'deepcopy': False,
                'thruput_controller': {
                    'push_sample_rate_limit': {
                        'max': float("inf"),
                        'min': 0
                    },
                    'window_seconds': 30,
                    'sample_min_limit_ratio': 1
                },
                'monitor': {
                    'sampled_data_attr': {
                        'average_range': 5,
                        'print_freq': 200
                    },
                    'periodic_thruput': {
                        'seconds': 60
                    }
                },
                'cfg_type': 'AdvancedReplayBufferDict'
            },
            'eps': {
                'type': 'exp',
                'start': 1.0,
                'end': 0.02,
                'decay': 10000
            }
        },
        'type':
        'dqn',
        'cuda':
        False,
        'on_policy':
        False,
        'priority':
        True,
        'priority_IS_weight':
        True,
        'discount_factor':
        0.99,
        'nstep':
        1,
        'cfg_type':
        'DQNPolicyDict',
        'load_path':
        '/home/mhx/RLlib/DI-engine/DI_rl_2022-09-03_16-44-12/ckpt/iteration_820.pth.tar'
    },
    'exp_name': 'DI_rl_2022-11-06_21-15-38',
    'seed': 0
}
```

Other hypermeters is default. For RLlib, default hypermeters are shown in  https://docs.ray.io/en/latest/rllib/rllib-training.html#common-parameters  and  https://docs.ray.io/en/latest/rllib/rllib-algorithms.html#deep-q-networks-dqn-rainbow-parametric-dqn

Convergence result of DQN in RLlib and DI-engine are shown in https://docs.qq.com/s/bnKe7iAPM-dKkruoH0b3uq

**Comment by mahuangxu** [comment]
我有几种猜测：
1.二者的神经网络初始化方式不同（我使用了GAT神经网络）？
2.二者的DQN算法版本不同？
3.二者的采样逻辑不同？
目前我正在逐一测试，试图找到性能相差的原因

**Comment by PaParaZz1** [comment]
应该是超参数设置的问题，完全简单对齐超参数其实内部还是有很多不一致，对于目前的收敛性问题，我建议的分析思路如下：
- 首先根据你提供的图片，目前DI-engine的版本其实处于reward基本没有上升的状态，这里首先应该检查探索相关，对于DQN那就是eps-greedy，虽然你目前的设置看起来一样，但是我不确定DI-engine的`decay`和RLlib的`epsilon_timesteps`是否是相同单位，DI-engine的decay对应的是env step（即和环境交互的次数），感觉设置成1w可能太小了，很容易还没学到什么eps就衰减到很低了。另外，神经网络的初始化确实对DQN初始的探索很有影响，理想情况是训练一开始让各个动作的Q值都维持在一个比较接近且绝对值较小的状态，这样就更不容易在训练一开始就落入某种局部极值。最后，也许你可以添加`random_collect_size=5000`参数，在训练一开始先随机收集一定量的数据，因为replay buffer一开始是空的，一开始随机收集一些可以减少初始阶段的不稳定。（可以参考这个[示例](https://github.com/opendilab/DI-engine/blob/main/dizoo/classic_control/cartpole/config/cartpole_sac_config.py#L13)）
- 如果探索方面确认没问题，那就要看利用（优化）部分了，这时候先检查采样逻辑，我看到你开启了PER，但也许你可以设置`priority=True`但是`priority_IS_weight=False`，因为后者虽然是PER原文中的设计，但是我们的实践经验中感觉经常是副作用，如果想开启`priority_IS_weight`则需要适当扩大学习率。在采样之外，就需要查看优化本身的一些指标，比如Q值的变化情况和loss的幅度，进而思考可能是哪些超参数影响优化（比如lr decay，grad norm之类的）。

希望可以帮到你，后续有进展可以在这个issue保持讨论。
