### ISSUE TITLE
训练时，后台日志太多

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#545]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [x] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.12.1+cu116 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
DI的后台刷新日志太多，能否尽量简洁？

比如下面为tianshou的后台，每个epoch第一行为训练，第二行为评估，epoch5是正在训练，训练时，使用了tqdm的功能，显示的值都会对应的变动，这样可以很直观的观察一段时间的训练和评估纵览。

![image](https://user-images.githubusercontent.com/26672425/202637431-e95cfd3e-39f2-43c1-be86-906e187e522c.png)

**Comment by PaParaZz1** [comment]
原始log一般就是比较琐碎的，你可以通过控制log的level来选信息。一般实验结果主要还是看tensorboard和wandb。tianshou这样用tqdm的模式，在分布式条件下整合起来比较费劲，我们可以尝试做一个可选插件，让用户在原版log和简化版tqdm log中二选一。

**Comment by jaried** [comment]
那就不用改了，我看tensorboard或者wandb吧。
