### ISSUE TITLE
Training, Saving, Loading and Evaluating the Model with Additional Features 

### ISSUE THREAD

**Issue by chadee1x** [opendilab/DI-engine#552]
Hi i would have a few follow-up questions with respect to recently closed issue

https://github.com/opendilab/DI-engine/issues/546

I was wandering how we can:

1. Save the best model - it looks like during the training the best model is saved in: ./stocks_dqn_seed0_221125_043003/ckpt/iteration_0.pth.tar
Is this the best model?

2. Load the saved model

3. Evaluate loaded model on out of sample data

4. Specify trading fees

5. Normalize the reward and features for training and use it in the same way during model evaluation on the testing data

6. Incorporate additional features i.e. in addition to OHLC, Volume and Adj. Close, how to modify the code so that the model uses TA indicators specified as a time series and stored as additional columns in the pandas data frame.

7. Specify the column name for pricing data (Now 'Close" or "Adjusted close" is used)

8. Access action space data and particular reward - for example to map actions (buy, sell, hold) onto a pricing data frame as an additional column.

I would appreciate any help that would make these working.

**Comment by Cloud-Pku** [comment]
1. The best model will be saved as "./stocks_dqn_seed0_xxxxx/ckpt/ckpt_best.pth.tar". And iteration_xxx.pth.tar is the model after xxx training iterations.
2. If you want to load the saved model, you can config the field stocks_dqn_config.policy.learn.learner.hook.load_ckpt_before_run = "the model path".
Like this:
<img width="593" alt="Q2" src="https://user-images.githubusercontent.com/73453791/205546365-f23c528f-cb03-4e96-9770-1c8bc5129a0c.png">

3. If you want to test your model on unseen data, you can config the field "train_range" as well as "test_range", which will continue to test during training. If you want to test and analyse after training, you can split the raw data file and write a new pipeline.
4. You can define it at [here](https://github.com/opendilab/DI-engine/blob/e028d368729b1fa6e7719dff0a3d48f120d8f950/dizoo/gym_anytrading/envs/stocks_env.py#L38)
5. You can nomalize the feature at [here](https://github.com/opendilab/DI-engine/blob/e028d368729b1fa6e7719dff0a3d48f120d8f950/dizoo/gym_anytrading/envs/stocks_env.py#L31) and [reward](https://github.com/opendilab/DI-engine/blob/e028d368729b1fa6e7719dff0a3d48f120d8f950/dizoo/gym_anytrading/envs/stocks_env.py#L92). Actually, the way applied to normalize is quite simple, it may be more effective to adjust the regularization method of features such as "close" to the overnight change rate.
6. It will certainly be effective to add other technical indicators as features, you can calculate the other indicators on the raw data and generate a new "csv" file. After that, you can load your new data file and select the features you want at [here](https://github.com/opendilab/DI-engine/blob/e028d368729b1fa6e7719dff0a3d48f120d8f950/dizoo/gym_anytrading/envs/stocks_env.py#L55). 
But if you want to modify the source code to achieve this requirement, it's suggested that you can rewrite the __process_data_ function, which will be called before env.reset(). 
7. Maybe you can set the column name by assigning a value to dataframe.index.
8. You can get the data you want and record them from [here](https://github.com/opendilab/DI-engine/blob/e028d368729b1fa6e7719dff0a3d48f120d8f950/dizoo/gym_anytrading/envs/trading_env.py#L157).

**Of course, you are welcome to contribute code to improve this project!**
