### ISSUE TITLE
请问，masac如何让action屏蔽非法动作？

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#556]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.4 1.12.1+cu116 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] win32
```
我之前用reward惩罚的方式，发现效果不好。查阅相关资料，用action mask可能更合适一些，但是是否非法得由env确定。

DI是否支持action mask屏蔽非法动作？有没有Demo?

**Comment by PaParaZz1** [comment]
- 确实使用`action mask` 要比惩罚性 reward 好很多。前者用起来方便，可以帮助精简梯度流。后者要操控这个惩罚奖励的权重就很麻烦了。
- DI-engine 在离散的多智能体算法中都实现了这一点，包括 QMIX，MAPPO，MASAC，以及我们新推出的 [ACE](https://github.com/opendilab/ACE)。具体代码，比如 MASAC的话，其实你只需要把 `action_mask` 作为obs的一部分从环境传出来就好了，相关应用`action_mask`的代码实现在[模型](https://github.com/opendilab/DI-engine/blob/main/ding/model/template/maqac.py#L164)和[模型wrapper](https://github.com/opendilab/DI-engine/blob/main/ding/model/wrapper/model_wrappers.py#L554)。

**Comment by jaried** [comment]
谢谢您的回答。

**Comment by jaried** [comment]
请问，连续动作支持`action mask`吗？
比如，我的`action_space`是：
```python
        self._action_space = _action_space = gym.spaces.Dict(
            {f'agent_{x}': gym.spaces.Box(low=-1, high=1, shape=(3,), dtype=np.float32) for x in
             range(4)}
        )
```
假如agent_0需要把动作屏蔽掉，那
```python
obs['action_mask']=[[0,0,0],[1,1,1],[1,1,1],[1,1,1]]
```
还是
```python
obs['action_mask']=[[0],[1],[1],[1]]
```
还是其他值？

**Comment by PaParaZz1** [comment]
连续动作目前未支持，不过你可以这样操作：
- 环境里给出`action_mask`，`obs['action_mask']=np.array([0, 1, 1, 1])
- 在神经网络的实现里，把mask为0的部分对应的输出（比如SAC里就是mu和sigma）给detach掉，这样外面计算梯度就不会反传回这些mask为0的部分了。否则常规的做法要修改policy，工作量就大了。

**Comment by jaried** [comment]
我想了一个更简单的方法，直接把非法的action 在env里面clip到合适的值。
