### ISSUE TITLE
pynng.exceptions.DestinationUnreachable

### ISSUE THREAD

**Issue by Wybgit89** [opendilab/DI-engine#559]
I ran the example atari-dqn-dist.yaml example with the nightly image, following is the err log.
[err.log](https://github.com/opendilab/DI-engine/files/10242072/err.log)
I do not know the reason.

**Comment by sailxjx** [comment]
This seems to be some problem with your local network configuration, need more information to determine the cause, can you paste the content of atari-dqn-dist.yaml below?

**Comment by Wybgit89** [comment]
Following is the yaml I used. I changed the ding nightly image by install a lower version of pytorch 1.7.0 as my cuda version is low.
[atari-dqn-dist-mount-test.txt](https://github.com/opendilab/DI-engine/files/10284559/atari-dqn-dist-mount-test.txt)

**Comment by sailxjx** [comment]
I see you used `echo $DI_RANK;echo $DI_NODES;` on the top of the script, so what do these two statements print?

**Comment by Wybgit89** [comment]
echo $DI_RANK print “3”
echo $DI_NODES print “job-with-tasks-learner-0.di-job-with-tasks.default.svc.cluster.local,job-with-tasks-evaluator-0.di-job-with-tasks.default.svc.cluster.local,job-with-tasks-collector-0.di-job-with-tasks.default.svc.cluster.local,job-with-tasks-collector-1.di-job-with-tasks.default.svc.cluster.local”

**Comment by sailxjx** [comment]
This problem may be in your k8s routing, you can try the following two steps:
1. Try to ping other containers and check the logs, for example `ping job-with-tasks-collector-1.di-job-with-tasks.default.svc.cluster.local`
2. Put all these scripts in one container to see if they can run. You can use & at the end of each command to let it run in the background and use `sleep 1000` to keep the container alive.
