### ISSUE TITLE
ngu is not completed? reward_intrinsic have not been added

### ISSUE THREAD

**Issue by Seven-deng** [opendilab/DI-engine#566]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```

**Comment by puyuan1996** [comment]
Hello,

Thanks for you question. Can you explain your question in detail? Especially what does `reward_intrinsic have not been added` mean? In our [NGU implementation](https://github.com/opendilab/DI-engine/blob/main/ding/reward_model/ngu_reward_model.py), the inter-episodic_intinsic reward and episodic_intinsic reward is already implemented.

Look forward to your reply!
Good Luck!
