### ISSUE TITLE
Examples for using Imitation Learning / Offline RL Algorithms

### ISSUE THREAD

**Issue by batu** [opendilab/DI-engine#576]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [X] documentation request
    + [ ] new feature request
- [X] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [X] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [N/A] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```
Hello, first of all thank you for this great looking open source project!

I am interested in comparing Implicit BC to other RL algorithms. I have of course seen the workflow to use the RL algorithms, but I couldn't find documentation on how to load data for BC/Offline RL algorithms. 

Would documentation on that be possible?

Thank you

**Comment by PaParaZz1** [comment]
Thanks for you interests for our repo. 

For the data pipeline of BC/offline training, including generating data, loading data, offline training and other steps, we will add a `best practice` documentation in this week, you can follow this issue and add your comments.

**Comment by PaParaZz1** [comment]
@batu You can refer to this [PR](https://github.com/opendilab/DI-engine-docs/pull/220) and give some review comments.
