### ISSUE TITLE
Problem with DQfD doc

### ISSUE THREAD

**Issue by Seraphli** [opendilab/DI-engine#585]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```
v0.4.5 1.12.1+cu102 3.9.16 (main, Jan 30 2023, 17:28:55) 
[GCC 12.2.0] linux

Hi, I'm new here. I'm trying to run DQfD. The command `ding -m serial_dqfd -c cartpole_dqfd_config.py -s 0` is not working. So I tried to run inside `dizoo/classic_control/cartpole/config`, and it pops out with `Enter the name of the config you used to generate your expert model:` What should I type? And How can I replicate the benchmark shown in the doc?

And another thing is that the benchmark compares DI-Engine with sb3 and tianshou on DQfD, but I can not find the algorithm in sb3 and tianshou. This confuses me.

**Comment by PaParaZz1** [comment]
We have polished DI-engine's DQfD doc. The DQN results of SB3 and tianshou were used in this doc before, which is indeed easy to cause ambiguity. Now it is removed in latest version.

**Comment by PaParaZz1** [comment]
I have recorded a naive demo about how to run `cartpole + DQfD` in container ([link](https://github.com/PaParaZz1/tbdata/blob/main/dqfd/dqfd_demo.mp4)), you can refer to this demo. If you have other problems, you can continue to feedback in this issue.

**Comment by Seraphli** [comment]
I check out the video and thanks I get it. There is still one thing about the doc. The evaluation graph contains several curves. What algorithm the color stands for?

**Comment by PaParaZz1** [comment]
> I check out the video and thanks I get it. There is still one thing about the doc. The evaluation graph contains several curves. What algorithm the color stands for?

Different curves means different random seed.

**Comment by Seraphli** [comment]
Okay, thanks!
