### ISSUE TITLE
有没创建自己环境的教程

### ISSUE THREAD

**Issue by monkeycc** [opendilab/DI-engine#587]
我觉得最难的还是如何创建自己的环境

比如 超级马里奥
我用FC NES模拟器

我可以用
OCR识别数字 
可以用目标检测物体和人物 返回游戏中对应的图像坐标和人物名

我得到 数字 人物物体坐标
之后怎么办
如何创建自己的环境 ？
有没这样的教程？

**Comment by PaParaZz1** [comment]
在代码层面，如何将自定义环境接入到DI-engine里，可以参考这个[文档](https://di-engine-docs.readthedocs.io/zh_CN/latest/04_best_practice/ding_env_zh.html)

在算法设计层面，如何将一个自然决策问题，转化为适合于强化学习的环境，可以参考我们的入门公开课[PPO × Family](https://github.com/opendilab/PPOxFamily)，其中第二讲和第三讲就在具体讲如何设计动作空间（输出）和观察空间（输入）。
