### ISSUE TITLE
How to run d4rl baselines

### ISSUE THREAD

**Issue by Seraphli** [opendilab/DI-engine#593]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request

I check the config in the d4rl, and it only contains dict. How to run the code?

**Comment by PaParaZz1** [comment]
You can use the entry file like [this](https://github.com/opendilab/DI-engine/blob/main/dizoo/d4rl/entry/d4rl_cql_main.py) to run related demo.

For runtime environment, you can try our docker image `opendilab/ding:nightly-d4rl`

**Comment by Seraphli** [comment]
Why those python codes are using absolute paths?

**Comment by PaParaZz1** [comment]
> Why those python codes are using absolute paths?

Because relative path often leads to some problems. Is there anything wrong in your environment?

**Comment by Seraphli** [comment]
There are some problems in the current code.
1. dependency should be changed to https://github.com/Farama-Foundation/D4RL
2. di-engine 0.4.6 requires gym==0.25.1, which is conflict with D4RL requirements(gym<0.24.0).

**Comment by PaParaZz1** [comment]
Thanks for you feedback!
- For problem 1, we will update dependency in next version.
- For problem 2, we will raise a issue to official D4RL repo for the problem of gym version. But you can use this [fork](https://github.com/PaParaZz1/D4RL) counterpart which is compatible with gym==0.25.1

**Comment by Seraphli** [comment]
Thanks, I will check it out.
