### ISSUE TITLE
Document of SAC default config need to be updated

### ISSUE THREAD

**Issue by Seraphli** [opendilab/DI-engine#601]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)

It seems the default config document is copied from `td3`.

**Comment by PaParaZz1** [comment]
Thanks for you feedback, we will update this doc in 2~3 days.

**Comment by PaParaZz1** [comment]
We have updated related comments and doc in this commit (https://github.com/opendilab/DI-engine/commit/67032d7db17ec53be06d6e666bc9445bbea3816a).

**Comment by Seraphli** [comment]
Reporting another issue, NGU seems only to have the Chinese version document.
https://di-engine-docs.readthedocs.io/en/latest/12_policies/ngu_zh.html#id5
And is there any plan to provide baseline figures for NGU?

**Comment by PaParaZz1** [comment]
We are preparing the contributiors calling plan about algorithm zoo and related docs, are you willing to add an English version doc of NGU? We will provide the corresponding support. 

For the baseline figures for NGU, you can refer to #40.

**Comment by Seraphli** [comment]
Thanks for the baseline figures. I would like to contribute, but currently, I don't have much time. Maybe later.

**Comment by PaParaZz1** [comment]
OK, we will close this issue first. If you have the spare time to contribute related doc, you can raise a pull request in [DI-engine-docs](https://github.com/opendilab/DI-engine-docs) and let me know.

**Comment by Seraphli** [comment]
Okay
