### ISSUE TITLE
Tag v0.4.6 use __version__ 0.4.5

### ISSUE THREAD

**Issue by Seraphli** [opendilab/DI-engine#609]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [x] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)

https://github.com/opendilab/DI-engine/blob/v0.4.6/ding/__init__.py

**Comment by PaParaZz1** [comment]
This bug has fixed in https://github.com/opendilab/DI-engine/commit/0b4180c2880ef91b4f3c72c19d566027aeca33e2, but DI-engine's pypi 0.4.6 version has been released, so we can only correct this field in 0.4.7 version.

**Comment by Seraphli** [comment]
Okay. Glad to hear this is fixed.
