### ISSUE TITLE
Support for next generation of gym: gymnasium

### ISSUE THREAD

**Issue by jianzuo** [opendilab/DI-engine#612]
您好，
非常感谢开源提供DI-engine一系列工具和教程。我目前正在自己的课题上尝试使用这些工具。
我注意到gym的库已经停止更新了，转移到gymnasium中。请问DI-engine会考虑兼容gymnasium吗？

对于我的应用我主要是需要自己定义强化学习环境，之前是基于gym, gymnasium写的，所以想请教下这点。

**Comment by PaParaZz1** [comment]
谢谢你的关注，也欢迎反馈各种意见和建议，我们会尽可能地提供支持！
对于 gym 的版本更新问题，因为牵扯到太多下游具体的环境，有些原作者的升级维护也很慢，所以我们计划采用如下的规则
- 对于环境库本身已经升级到 gymnasium 的情况，我们会让 DI-engine 逐渐适配到最新版本，例如 pettingzoo 和 minigrid 就是已经升级后的状态。
- 对于那些尚未进行升级的环境库，我们会暂时固定在 gym=0.25.1 版本，如果原仓库作者迁移到了 gymnasium，我们会在一定时间内也进行更新。

**Comment by jianzuo** [comment]
谢谢您的解答！
我目前正在将自己的RL环境迁移到咱们的DI-engine中。
如果自己创建自定义环境，请问您建议是直接用gymnasium还是用gym(比如您说的0.25)?
后面有些问题我会继续更新请教，谢谢！

**Comment by PaParaZz1** [comment]
自定义环境的话，直接使用 gymnasium 即可，不过如果出现问题可以再提 issue 我们来帮助解决。
