### ISSUE TITLE
run dqn.py in docker 

### ISSUE THREAD

**Issue by LawranceXcl** [opendilab/DI-engine#613]
- [ ] I have marked all applicable categories:
    + [ ] system utils bug
![img_v2_9cb37ee0-4d71-448c-b581-3cc9c1ea7dcg](https://user-images.githubusercontent.com/47016472/225175207-6dff7496-8729-458a-9af1-1a9a73ae53ab.png)

**Comment by PaParaZz1** [comment]
This is a known bug about the update treevalue 1.4.9, maybe you can execute `pip3 install treevalue==1.4.6` to skip this bug temporally. And we will fix this bug in next version of treevalue as soon as possible.

**Comment by PaParaZz1** [comment]
We have fixed this problem in treevalue 1.4.10 ([link](https://github.com/opendilab/treevalue/releases/tag/v1.4.10)).
