### ISSUE TITLE
the use of BaseSerialCommander and ppo_command

### ISSUE THREAD

**Issue by zhixiongzh** [opendilab/DI-engine#632]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```
`
v0.4.6 1.10.0 3.7.11 (default, Jul 27 2021, 14:32:16)`

Hi,

I do not find any ducumentation explaining the use class **BaseSerialCommander** and the policy **policy_command**, e.g. ppo_command, what is the difference to ppo without command.

Best

**Comment by PaParaZz1** [comment]
`commander` is a old version design to unify the algorithm information communication between different workers. 

For example, if we need to control some hyper-parameter in `collector` adaptively, we have to first fetch several training statistics in `learner` then modify this parameter.

As for the basic PPO, it doesn't need these communication operation so that `ppo_command` is just an empty interface.

In the latest task pipeline, we have removed the design of `commander`.

**Comment by zhixiongzh** [comment]
> `commander` is a old version design to unify the algorithm information communication between different workers.
> 
> For example, if we need to control some hyper-parameter in `collector` adaptively, we have to first fetch several training statistics in `learner` then modify this parameter.
> 
> As for the basic PPO, it doesn't need these communication operation so that `ppo_command` is just an empty interface.
> 
> In the latest task pipeline, we have removed the design of `commander`.

Thanks for the explaination.

I see that commander is not used in the task pipeline an in the cartpole_ppo_main.py, but still used in the serial_entry_onpipeline. It seems you are working towards making all algorithm working using task, but basically all the example  in dizoo are in serial pipeline. Where can I find more examples in task format instead of serial pipeline.
