### ISSUE TITLE
Unify main_config and create_config into one config

### ISSUE THREAD

**Issue by way-zer** [opendilab/DI-engine#633]
I am trying to rework on `compile_config` to implemation this.  
see https://gist.github.com/way-zer/8edc119b19d654e91fdbc04687d64a1a  
Get same output for `cartpole_dqn_config`. 
There are many advantages:
* no need to know what is `create_config`.
* new code and new config is more concise.
* `compile_config(total_config) == total_config`, no need `formatted`.

---

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [x] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```
```
v0.4.6 1.12.1 3.8.15 (default, Nov  4 2022, 20:59:55) 
[GCC 11.2.0] linux
```

---

**Comment by PaParaZz1** [comment]
It's really a nice try. Let me reclaim your config design:
- delete create_config, move `type` and `import_names` to the corresponding field of main_config
- if `type` and `import_names` are indicated in user config, this method will use `get_xxx_cls` to acquire the corresponding class, if not the program will use the default class.

BTW, for the sake of compatibility, I suggest that you should rename this new method like `tiny_compile_config` or `fast_compile_config`. After modification, you can raise a pull request to DI-engine and let us work together to merge it into main branch.
