### ISSUE TITLE
redundant operation in to_tensor_transitions [bug]

### ISSUE THREAD

**Issue by zhixiongzh** [opendilab/DI-engine#638]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
   v0.4.6 1.10.0 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0] linux
  ```
https://github.com/opendilab/DI-engine/blob/1cb1038aca287a06a7f8fb1cf35f15cc9636e0cd/ding/worker/collector/base_serial_collector.py#L217-L224

There seems to be a redundant operation.

If I understand correcly, Line 219 should be deleted for saving memory of next_obs

**Comment by PaParaZz1** [comment]
line 219 was added to fix the problem mentioned in #342, we will add extra option to control whether to use deepcopy.
