### ISSUE TITLE
Unresolved for 18 Months: Issue #90 - League Training for SlimeVolleyball Env

### ISSUE THREAD

**Issue by zxzzz0** [opendilab/DI-engine#645]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [x] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)

### Overview
Add league training pipeline in slime_volleyball environment, and make better performance than self-play results (https://github.com/opendilab/DI-engine/pull/23)
Related Discussion: https://github.com/opendilab/DI-engine/discussions/61

---

I hope this message finds you well. I am writing to bring your attention to issue #90, which was created 18 months ago and has not been resolved yet. This issue concerns the league training in reinforcement learning, specifically for the "SlimeVolleyball" environment.

The original issue highlights the problem users have been experiencing with the league training component in the "SlimeVolleyball" environment. Many users have reported that the league training is not functioning as intended, leading to poor agent performance and limited improvements over time. 

As this is a significant issue impacting users' ability to effectively train their agents in the "SlimeVolleyball" environment, I kindly request you to prioritize fixing this issue. The community would greatly benefit from an update on this topic, as well as any progress you've made or any assistance you may need from the community.

I understand that managing and maintaining a project can be challenging, and I appreciate your hard work on this. However, given the importance of this issue, your attention to it would be highly appreciated.

Thank you for your time and consideration. We look forward to your response and any updates you may have on this matter.

**Comment by PaParaZz1** [comment]
At present, we don't have plan to continue the tutorial demostartion about league training in slime_volleyball environment. In the previous pull request, we find that directly applying the league designed in AlphaStar shows few gain in this environment. It will takes some additional efforts to specialize a league training scheme for slime_volleyball.

BTW, we are working on MCTS/MuZero techniques in this [LightZero](https://github.com/opendilab/LightZero), maybe we can try to design a example about league training in some board games, e.g. gomuku.

**Comment by zxzzz0** [comment]
> It will takes some additional efforts to specialize a league training scheme for slime_volleyball.

What are the "some additional efforts"? Could you please give more details

**Comment by zxzzz0** [comment]
@PaParaZz1

**Comment by zxzzz0** [comment]
@PaParaZz1 Could you please answer the question above? Thanks.
