### ISSUE TITLE
average value in log

### ISSUE THREAD

**Issue by zhixiongzh** [opendilab/DI-engine#649]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```
`v0.4.6 1.12.0 3.7.13 (default, Mar 29 2022, 02:18:16)  [GCC 7.5.0] linux`

after a few iterations, the training iteration result will be printed and recorded in tensorboard. When it comes to the `total_loss_avg`, in what dimension is this average taken? Is it the average for every 100 iterations or the average for the entire training process from start to now?

**Comment by PaParaZz1** [comment]
The specific average interval is set in this [line](https://github.com/opendilab/DI-engine/blob/main/ding/worker/learner/base_learner.py#L436), the current argument is `expire=10`, which means it is the average for each 10 iterations.

**Comment by zhixiongzh** [comment]
> The specific average interval is set in this [line](https://github.com/opendilab/DI-engine/blob/main/ding/worker/learner/base_learner.py#L436), the current argument is `expire=10`, which means it is the average for each 10 iterations.

Thanks! This is very clear.
