### ISSUE TITLE
使用自己的专家轨迹

### ISSUE THREAD

**Issue by nianba** [opendilab/DI-engine#657]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
v0.4.7 2.0.0+cu117 3.9.0 (default, Nov 15 2020, 14:28:56) 
[GCC 7.3.0] linux

我最近尝试使用模仿学习来解决一项自动驾驶的问题，因此我很高兴能发现DI-engine，它有许多先进的模仿学习算法与详细的文档。
但是在使用中，我碰到了一个问题。我在DI-engine中找到了关于模仿学习的最佳实践，但它似乎只阐述了如何使用一个已经训练好的model来生成专家轨迹，但在我的问题中，我没有一个训练好的model，只有一些收集好的专家轨迹（包括状态，动作，奖励等）。请问在这种情况下，我要如何使用DI-engine中的模仿学习算法，例如R2D3呢？
盼望收到您的回复，感谢！

**Comment by ruoyuGao** [comment]
首先，我对于延迟回复您表示深感抱歉。关于您的问题，目前DI-engine暂时没有提供直接调用专家数据的方法。然而，您可以考虑对r2d3的入口进行修改，以实现这个功能。这里是相关的链接：[r2d3入口](https://github.com/opendilab/DI-engine/blob/main/ding/entry/serial_entry_r2d3.py)

具体来说，您可以将“将expert collector收集的数据放入expert buffer”这部分修改为“将已经收集好的专家数据放入expert buffer”。这样，您可以从expert buffer这中采样您需要使用的数据。

值得注意的是，放入到expert data的数据应该是一个字典类型，它需要包含以下的键值对：
```python
'obs': List[torch.Tensor]
'action' : List[torch.Tensor]
'prev_state' : List[torch.Tensor]
'reward' : List[torch.FloatTensor]
'done' : List[torch.BoolTensor]
'collect_iter' : List[int]
'value_gamma' : List[torch.Tensor]
'done_one_step' : List[torch.BoolTensor]
```

其中，'done'指的是在n个时间步后环境是否结束(n需要人为定义，且和config中的nstep保持相同)，'done_one_step'表示下一个时间步是否结束，'collect_iter'表示这是哪个迭代的专家收集来的。对于您的情况，'collect_iter'的值应默认为-1。'value_gamma'是我们在计算td error中使用的discount factor。

希望这个答复对您有所帮助，如果您有任何其他问题，欢迎随时向我提问。

**Comment by nianba** [comment]
十分感谢您详细的答复，我会着手测试您答复中所描述的方法，并第一时间将结果在这个issue中告知。
再次感谢！
