### ISSUE TITLE
Multi GPU training problem

### ISSUE THREAD

**Issue by zqh0253** [opendilab/DI-engine#66]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc]()
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```

My DING's version is f1bf66. My pytorch version is 1.7.1+cu101. My system is Linux 3.7.11 (default, Jul 27 2021, 14:32:16) \n[GCC 7.5.0].
I follow the docs' guidance to enable multi-gpu training. I add a config term **config.policy.learn.multi_gpu=True** in demo/simple_rl/ppo_train.py. But I get the following exception:

WARNING:root:If you want to use numba to speed up segment tree, please install numba first
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[ENV] Setting seed: 0
Traceback (most recent call last):
  File "imgppo_train.py", line 189, in <module>
    main(main_config)
  File "imgppo_train.py", line 158, in main
    policy = PPOPolicy(cfg.policy, model=model)
  File "/home/qhzhang/code/DI-engine/ding/policy/base_policy.py", line 81, in __init__
    self._init_multi_gpu_setting(model)
  File "/home/qhzhang/code/DI-engine/ding/policy/base_policy.py", line 101, in _init_multi_gpu_setting
    broadcast(param.data, 0)
  File "/home/qhzhang/anaconda3/envs/didrive/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 859, in broadcast
    _check_default_pg()
  File "/home/qhzhang/anaconda3/envs/didrive/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 211, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized

**Comment by zqh0253** [comment]
The file demo/simple_rl/ppo_train.py is in [DI-drive repo](https://github.com/opendilab/DI-drive/blob/fe7e4d4dc4db9669d1aabc6fc63eb5339574411b/demo/simple_rl/ppo_train.py)

**Comment by PaParaZz1** [comment]
You can refer to this [demo](https://github.com/opendilab/DI-engine/blob/main/dizoo/atari/config/serial/pong/pong_dqn_multi_gpu_config.py#L60) and add `DistContext` in your program

**Comment by zqh0253** [comment]
Thanks for your suggestion. But I add DistContext and get the following error:

WARNING:root:If you want to use numba to speed up segment tree, please install numba first
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "imgppo_train.py", line 189, in <module>
    with DistContext():
  File "/home/qhzhang/code/DI-engine/ding/utils/pytorch_ddp_dist_helper.py", line 114, in __enter__
    dist_init()
  File "/home/qhzhang/code/DI-engine/ding/utils/pytorch_ddp_dist_helper.py", line 81, in dist_init
    raise RuntimeError("please indicate rank explicitly in dist_init method")
RuntimeError: please indicate rank explicitly in dist_init method

**Comment by PaParaZz1** [comment]
Are you run multi-gpu program in your own machine? And I guess you should prepare related environment variables [here](https://github.com/opendilab/DI-engine/blob/main/ding/utils/pytorch_ddp_dist_helper.py#L97). 

We test this parts in slurm before so it would be a bit inconvenient in local machine. And you can add your own advice for multi-gpu training in local machine.

**Comment by zqh0253** [comment]
I am running multi-gpu program in my own machine so your code based on slurm environment does not work. 
I have gone through the relevant code about multi-gpu part. I think using `torch.distributed.launch` may help user to use your multi-gpu code in local machine.
But another problem for me is that I am actually using DI-drive and one di-drive program will launch several (like 8) carla environments. When using `torch.distributed.launch`, the carla will be launched multiple times (like 8*N, the N is gpu num). 
So I find a quick fix using `torch.DataParallel` to do multi-gpu training without your API.

**Comment by PaParaZz1** [comment]
OK, we will support `torch.DataParallel` in next version, for some cases like you encountered.

**Comment by WangJuan6** [comment]
Hi, @PaParaZz1 
I have the same error, can you provide a demo of how to use multi-GPU in the custom environment?
Thanks
