### ISSUE TITLE
Implementation of model-based RL algorithm Dreamer

### ISSUE THREAD

**Issue by openRiemann** [opendilab/DI-engine#669]
Thanks for the amazing project!

Can you provide the implementation of model-based RL algorithm **Dreamer** from paper _[Dream to Control: Learning Behaviors by Latent Imagination](https://openreview.net/pdf?id=S1lOTC4tDS)_? Implementation from [ray-project/ray](https://github.com/ray-project/ray/tree/master/rllib) is too cumbersome.

**Comment by PaParaZz1** [comment]
Thanks for your interests. We are planning to add supports for DreamerV3 (e.g. #652). You can keep track of this issue for further updates.

**Comment by openRiemann** [comment]
> 

Thanks!

**Comment by openRiemann** [comment]
> Thanks for your interests. We are planning to add supports for DreamerV3 (e.g. #652). You can keep track of this issue for further updates.
Thanks!

**Comment by openRiemann** [comment]
> Thanks for your interests. We are planning to add supports for DreamerV3 (e.g. #652). You can keep track of this issue for further updates.

Thanks!

**Comment by PaParaZz1** [comment]
We have implemented dreamerv3 and tested its performance in #652.
