### ISSUE TITLE
`dqn_rnd.py` example appears to be incorrect

### ISSUE THREAD

**Issue by ahalev** [opendilab/DI-engine#676]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [x] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```

```python
ding.__version__='v0.4.8', torch.__version__='2.0.1', sys.version='3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) \n[Clang 14.0.6 ]', sys.platform='darwin'
```

When examining the example `ding/examples/dqn_rnd.py` I noticed a couple of issues:

1) The RND training function `RndRewardModel.train` is never called, so the rnd model is never updated
2) `OffPolicyLearner._reward_estimator(ctx)` performs an in-place modification of `ctx` to modify the rewards. This method calls  `RndRewardModel.estimate`, which specifically performs a deepcopy of the rewards in `ctx` (line 169 in ding.reward_model.rnd_reward_model.py). As a result, the rewards in `ctx.train_data` are not modified in place and intrinsic rewards are never passed to the data used in DQN model training. Note that other reward models (e.g. `RndNGURewardModel`) do not perform this deepcopy.

**Comment by ahalev** [comment]
Also, the functional programming + in-place modifications of `ctx` variables make it very hard to keep track of what's happening where...

**Comment by PaParaZz1** [comment]
> * [x]  I have marked all applicable categories:
>   
>   * [ ]  exception-raising bug
>   * [x]  RL algorithm bug
>   * [ ]  system worker bug
>   * [ ]  system utils bug
>   * [x]  code design/refactor
>   * [ ]  documentation request
>   * [ ]  new feature request
> * [x]  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
> * [x]  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
> * [x]  I have mentioned version numbers, operating system and environment, where applicable:
>   ```python
>   import ding, torch, sys
>   print(ding.__version__, torch.__version__, sys.version, sys.platform)
>   ```
> 
> ```python
> ding.__version__='v0.4.8', torch.__version__='2.0.1', sys.version='3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) \n[Clang 14.0.6 ]', sys.platform='darwin'
> ```
> 
> When examining the example `ding/examples/dqn_rnd.py` I noticed a couple of issues:
> 
> 1. The RND training function `RndRewardModel.train` is never called, so the rnd model is never updated
> 2. `OffPolicyLearner._reward_estimator(ctx)` performs an in-place modification of `ctx` to modify the rewards. This method calls  `RndRewardModel.estimate`, which specifically performs a deepcopy of the rewards in `ctx` (line 169 in ding.reward_model.rnd_reward_model.py). As a result, the rewards in `ctx.train_data` are not modified in place and intrinsic rewards are never passed to the data used in DQN model training. Note that other reward models (e.g. `RndNGURewardModel`) do not perform this deepcopy.

This example is indeed not effective, maybe you can use the old entry [here](https://github.com/opendilab/DI-engine/blob/main/dizoo/box2d/lunarlander/config/lunarlander_rnd_onppo_config.py). We will polish this new example in a week.
