### ISSUE TITLE
Document about config

### ISSUE THREAD

**Issue by webbery** [opendilab/DI-engine#682]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```
version: v0.4.8
```
This is my first time using DI-engine. I run mario example in docker. Util 8 hours later it still running. It seems that `BaseLearner` set iterator times is `int(10^9)`.

I try to change `train_iterations` value but in `total_config.py` and `formatted_total_config.py` it still keep `1000000000` value :
```
    learner = BaseLearner(cfg.policy.learn.learner, policy.learn_mode, tb_logger, exp_name=cfg.exp_name)
    learner.config['train_iterations'] = 1000
    learner._cfg['train_iterations'] = 1000
```
 Can you give me some example about `config` module?

**Comment by PaParaZz1** [comment]
For the overview of the config in DI-engine, you can refer to [this doc](https://di-engine-docs.readthedocs.io/zh_CN/latest/03_system/config_zh.html).

For the termination of the entire program, you can refer to this code [line](https://github.com/opendilab/DI-engine/blob/main/ding/entry/serial_entry.py#L117).

**Comment by webbery** [comment]
So I can not change config to terminate the program. It's strange that config can not be config.  
And I didn't find 'render_mode' setting in config. Is it `di-engine` suport? Jupyter report warning that `render mode is None` then output video is empty.

**Comment by PaParaZz1** [comment]
The problem you said is indeed a throublesome thing. There are many ways for terminating the training program, such as max env step, max train iter, stop value or even training without clearly termination. Therefore, we don't set related config field and leave this in the main function of the entry file. If you have some customed demands, you need to write your own entry file like the default case listed in `ding/entry` directory.

For the problem of `render_mode`, DI-engine doesn't support this argument and add another `enable_save_replay` method to save replay videos, you can have a try for this method.

**Comment by webbery** [comment]
`enable_save_replay` is called.

The video is not generated because `libx264` is not find. In docker, ffmpeg is configure with `--enable-libopenh264`. It seem that `ffmpeg` not work correctly. So I recompile it with `--enable-libx264` and then it work.

**Comment by PaParaZz1** [comment]
> `enable_save_replay` is called.
> 
> The video is not generated because `libx264` is not find. In docker, ffmpeg is configure with `--enable-libopenh264`. It seem that `ffmpeg` not work correctly. So I recompile it with `--enable-libx264` and then it work.

Thanks for your feedback! We will add this problem into the FAQ part of doc.

**Comment by webbery** [comment]
Another question:
How to use `framework.task`? If task run, how to terminate it in my `max_train_iter`? If I run `mario` game and want to visualize some info, what should I do?

Can you give me a guide?
