### ISSUE TITLE
`enable_save_figure()` has no detailed document, and its comment is wrong.

### ISSUE THREAD

**Issue by shenpengfii** [opendilab/DI-engine#688]
The official document does offer any information for `enable_save_figure()`, one of the interfaces from the class `BaseEnvManager`. It interrupted when I want a simple method to display the reward-episode chart, but I have to go for the raw code:

```python
def enable_save_figure(self, env_id: int, figure_path: Union[List[str], str]) -> None:
        """
        Overview:
            Set each env's replay save path.
        Arguments:
            - replay_path (:obj:`Union[List[str], str]`): List of paths for each environment; \
                Or one path for all environments.
        """
        if isinstance(figure_path, str):
            self._env[env_id].enable_save_figure(figure_path)
        else:
            raise TypeError("invalid figure_path arguments type: {}".format(type(figure_path)))
```

Then I found the comment of Arguments distinguished with itself. It seems the comment is the same as the method `enable_save_replay()`, shown as follow:
```python
def enable_save_replay(self, replay_path: Union[List[str], str]) -> None:
        """
        Overview:
            Set each env's replay save path.
        Arguments:
            - replay_path (:obj:`Union[List[str], str]`): List of paths for each environment; \
                Or one path for all environments.
        """
        if isinstance(replay_path, str):
            replay_path = [replay_path] * self.env_num
        self._env_replay_path = replay_path
```

And I want to know where to learn the function of `enable_save_figure()`？ Is it a method for showing the rewards chart?

**Comment by PaParaZz1** [comment]
Thanks for your feedback. I have fixed this problem in this commit (https://github.com/opendilab/DI-engine/commit/49f2e209f5a8a9e7520595995bc34581f6f35470). And you can refer to this environment for the specific [example](https://github.com/opendilab/DI-engine/blob/main/dizoo/beergame/envs/beergame_env.py#L68) of this method.

**Comment by PaParaZz1** [comment]
> How can I confirm the parameter `env_id` of `enable_save_figure()`?

You can refer to the code implementation [here](https://github.com/opendilab/DI-engine/blob/main/ding/worker/collector/interaction_serial_evaluator.py#L237). If you have other demands, you can modify evaluator to implement it.
