### ISSUE TITLE
Does model support multiple input parameters?

### ISSUE THREAD

**Issue by webbery** [opendilab/DI-engine#689]
Hi,
Some models such as GNN require 2 params. For example:
```python
class GCNLayer(nn.Module):
    def forward(self, node_feats, adj_matrix):
        pass
```
Does `DI-engine` support this case? I can't find any example in source code. [Guild](https://di-engine-docs.readthedocs.io/en/latest/04_best_practice/custom_model.html) only give one situation.

**Comment by PaParaZz1** [comment]
You need to wrap your input into a dict two keys, (e.g. `{'node_feats': xxx, 'adj_matrix': xxx}`). Then unpack the data inside of the `forward` method. DI-engine designs one argument to ensure some general operations between different modules.

BTW, if you want to do some operations on dict-like data more conveniently, you can have a look about this [repo](https://github.com/opendilab/DI-treetensor) we provided.
