### ISSUE TITLE
`GAIL` the algorithm performs much worse than from its original paper.

### ISSUE THREAD

**Issue by shenpengfii** [opendilab/DI-engine#692]
*Before proposing this issue, I have searched it on document, issues and search engine.*

My job is to reproduce the excellent performance of `GAIL` over `BC` in the setting of `Cartpole`, where the `GAIL` should at least perform the same level as the `BC`. And Both the `GAIL` and `BC` generate expert data by the pre-installed template of `off-policy PPO` ([the original paper](https://arxiv.org/abs/1606.03476) use `TRPO`).

However, the result of `GAIL` performs much worse than the `BC`, conflicting with the [paper]((https://arxiv.org/abs/1606.03476)) conclusion as well. On my PC, the `GAIL` takes at least 462 episodes to converge, while the `BC` taking only 80 episodes. By the way, I've set them with parameters as identical with the [paper](https://arxiv.org/abs/1606.03476) as I can. It's very disappointing.

I have to look into the entry function `serial_pipeline_gail()`, but to find it didn't work the way as the comment from [cartpole_dqn_gail_config.py](https://github.com/opendilab/DI-engine/blob/main/dizoo/classic_control/cartpole/config/cartpole_dqn_gail_config.py) tells:
> If collect_data is True, we will use this expert_model_path to collect expert data first, rather than we will load data directly from user-defined data_path.

But I find **whether or not the collect_data is True, the collected expert data wouldn't be used in training the `GAIL` model**:

```python
# Load expert data
if collect_data:
    if expert_cfg.policy.get('other', None) is not None and expert_cfg.policy.other.get('eps', None) is not None:
        expert_cfg.policy.other.eps.collect = -1
    if expert_cfg.policy.get('load_path', None) is None:
        expert_cfg.policy.load_path = cfg.reward_model.expert_model_path
    collect_demo_data(
        (expert_cfg, expert_create_cfg),
        seed,
        state_dict_path=expert_cfg.policy.load_path,
        expert_data_path=cfg.reward_model.data_path + '/expert_data.pkl',
        collect_count=cfg.reward_model.collect_count
    )
```

After the `collect_demo_data()`, **the expert_data seems not used by any following part, which may lead to the low performance of `GAIL`**.

I started with the `DI-engine` without too many days, and I hope to figure out whether there's a bug in the implementation of `GAIL`. It really matters since the deadline of my work would come soon. I need a very timely help!

**Comment by PaParaZz1** [comment]
`CartPole` is a very naive environment, so its performance will fluctuate significantly due to some randomness and hyper-parameters. I suggest that you should conduct experiment MuJoCo environment such as `Hopper`. You can refer to this [doc](https://di-engine-docs.readthedocs.io/en/latest/12_policies/gail.html#benchmark) for more results about previous experiments.

**Comment by PaParaZz1** [comment]
You can join our slack channel and continue to discuss this problem. ([related link](https://github.com/opendilab/DI-engine#feedback-and-contribution))
