### ISSUE TITLE
Halfcheetah has negative state in z position

### ISSUE THREAD

**Issue by zhixiongzh** [opendilab/DI-engine#697]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [x] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  v0.4.6 1.10.0 3.7.11 (default, Jul 27 2021, 14:32:16) 
  [GCC 7.5.0] linux
  ```
Hi,

I am running sac algorithm on the env halfcheetah-v3 following the default setting and using the standard pipeline `serial_pipeline` . The final return is 12000 so looks normal. But when I log the observation value to see the maximum and minimal value, I found that the min value of first state `z-coordinate of the front tip` is negative `-0.59`, which should always a positive value above the ground? Also, the maximum value of second state `angle of the front tip` is `10.05`, which is also abnormal as it is larger than `pi`. I am curious if there is any preprocess to the variables? The min and max value for `hopper` and `walker2d` is normal actually, so I think by default there are no any preprocess. 

Hope to get any hint from you about this. Thanks.

**Comment by zjowowen** [comment]
You can turn to this page https://github.com/openai/gym/issues/2932 for your information.

It seems that the so-called "the front tip" is "the head of the cheetah".
"rootz" in the document means "z translation". I think it could be a relative one. But I am not sure about the center of observation. 
It may be the mass center. Although it does not matter too much.
The OpenAI team does not make the document clear enough.
You could raise issue in the github of openai/gym for any thing misleading.

The DI-engine will not preprocess observation unless an env wrapper that change the original observation is added.
For example, to transform an image of 0~255 uint8 into -1~1 float.
You could print the env and check if any special wrapper that changes the original observation are added in a debug mode.

**Comment by zhixiongzh** [comment]
> You can turn to this page [openai/gym#2932](https://github.com/openai/gym/issues/2932) for your information.
> 
> It seems that the so-called "the front tip" is "the head of the cheetah". "rootz" in the document means "z translation". I think it could be a relative one. But I am not sure about the center of observation. It may be the mass center. Although it does not matter too much. The OpenAI team does not make the document clear enough. You could raise issue in the github of openai/gym for any thing misleading.
> 
> The DI-engine will not preprocess observation unless an env wrapper that change the original observation is added. For example, to transform an image of 0~255 uint8 into -1~1 float. You could print the env and check if any special wrapper that changes the original observation are added in a debug mode.

Thanks for the kind reply. Then it would be a unclear description of the document from Gym, I just want to make sure DI-engine does not do anything about the observation.
