### ISSUE TITLE
not compatible with gym_pybullet_drones env

### ISSUE THREAD

**Issue by zhixiongzh** [opendilab/DI-engine#714]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [x] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  v0.4.9 1.12.1 3.7.13 (default, Mar 29 2022, 02:18:16) 
  [GCC 7.5.0] linux
  ```
I use the docker you provide with `docker pull opendilab/ding:nightly-mujoco`, but the python version there is 3.7, which is imcompatible with the requirement of gym_pybullet_drones, which require python 3.10, so that I can not install that with offical steps as below
```
git clone https://github.com/utiasDSL/gym-pybullet-drones.git
cd gym-pybullet-drones/

conda create -n drones python=3.10
conda activate drones

pip3 install --upgrade pip
pip3 install -e . # if needed, `sudo apt install build-essentials` to install `gcc` and build `pybullet`
```
But in the di zoo you provide the test file of this environment, so I want to ask how you install this env package so that you can run the test file.

**Comment by zhixiongzh** [comment]
https://github.com/opendilab/PPOxFamily/issues/4#issuecomment-1691251161
I found you have used drones env in the course that you forked a old version of env, that is ok for me, but I still can not install the old version with your code.

**Comment by zjowowen** [comment]
Hi,

This repo [https://github.com/zjowowen/gym-pybullet-drones.git] is updated with the origin repo [https://github.com/utiasDSL/gym-pybullet-drones].

You can run the gym-pybullet-drones by:
conda create gym-pybullet-drones -n python=3.10
pip install setuptools==63.2.0
pip install git+https://github.com/zjowowen/gym-pybullet-drones@master
pip install DI-engine

**Comment by zhixiongzh** [comment]
Thanks, it fix the problem

**Comment by RibhavOjha** [comment]
@zhixiongzh after doing pip install git+https://github.com/zjowowen/gym-pybullet-drones@master, what did you do? like it got installed successfully for me, but then what? did you do : 
`git clone https://github.com/utiasDSL/gym-pybullet-drones.git
cd gym-pybullet-drones/

conda create -n drones python=3.10
conda activate drones

pip3 install --upgrade pip
pip3 install -e . # if needed, `sudo apt install build-essentials` to install `gcc` and build `pybullet``

after that?

**Comment by zhixiongzh** [comment]
> @zhixiongzh after doing pip install git+https://github.com/zjowowen/gym-pybullet-drones@master, what did you do? like it got installed successfully for me, but then what? did you do : `git clone https://github.com/utiasDSL/gym-pybullet-drones.git cd gym-pybullet-drones/
> 
> conda create -n drones python=3.10 conda activate drones
> 
> pip3 install --upgrade pip pip3 install -e . # if needed, `sudo apt install build-essentials` to install `gcc` and build `pybullet``
> 
> after that?

if it is successfully installed using `pip install git+https://github.com/zjowowen/gym-pybullet-drones@master`, then it is done, you do not need to do other things. If you are asking how to use it, please refer to `dizoo/gym_pybullet_drones/envs/test_ding_env.py`
