### ISSUE TITLE
entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by hugo921** [opendilab/DI-engine#718]
when i run my env，i have got this error below

[m:\Users\18931\anaconda3\envs\dienv\lib\site-packages\gymnasium\envs\registration.py](file:///M:/Users/18931/anaconda3/envs/dienv/lib/site-packages/gymnasium/envs/registration.py) in load_env_plugins(entry_point)
    266 def load_env_plugins(entry_point: str = "gymnasium.envs") -> None:
    267     # Load third-party environments
--> 268     for plugin in metadata.entry_points(group=entry_point):
    269         # Python 3.8 doesn't support plugin.module, plugin.attr
    270         # So we'll have to try and parse this ourselves

TypeError: entry_points() got an unexpected keyword argument 'group'

**Comment by PaParaZz1** [comment]
You can have a try to install `gymnasium==0.27.1`.
