### ISSUE TITLE
Flask version error import

### ISSUE THREAD

**Issue by juanmigutierrez** [opendilab/DI-engine#743]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ x] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:

I am running di-engine version 0.4.9. In linux I got the following error when importing flask

  ```python
import gym # Load the gym library, which is used to standardize the reinforcement learning environment
import torch # Load the PyTorch library for loading the Tensor model and defining the computing network
from easydict import EasyDict # Load EasyDict for instantiating configuration files
from ding.config import compile_config # Load configuration related components in DI-engine config module
from ding.envs import DingEnvWrapper # Load environment related components in DI-engine env module
from ding.policy import DQNPolicy, single_env_forward_wrapper # Load policy-related components in DI-engine policy module
from ding.model import DQN # Load model related components in DI-engine model module
from dizoo.box2d.lunarlander.config.lunarlander_dqn_config import main_config, create_config # Load DI-zoo lunarlander environment and DQN algorithm related configurations
  ```

  ```python
ImportError: cannot import name 'escape' from 'jinja2'
  ```

Nevertheless when trying to update flask to >2.2.2, it says the poetry 

  ```
  Because di-engine (0.4.9) depends on flask (>=1.1.2,<1.2.0)
   and no versions of di-engine match >0.4.9,<0.5.0, di-engine (>=0.4.9,<0.5.0) requires flask (>=1.1.2,<1.2.0).
  So, because app depends on both di-engine (^0.4.9) and flask (2.2.2), version solving failed.
  ```

How solve this dependency error ?

**Comment by juanmigutierrez** [comment]
Also colab example does not work sadly. I think there is a problem of versioning

**Comment by PaParaZz1** [comment]
You can try to install `flask==1.1.2` and `jinja2==3.0.3`. 

I also test the colab demo (cartpole + DQN) and find there is no version problem.

**Comment by juanmigutierrez** [comment]
Yes I had to installed it manually poetry add flask==1.1.2 and poetry add jinja2==3.0.3, Seems its working now thanks.
