### ISSUE TITLE
How can I use the algorithm I designed (such as a new multi-agent reinforcement learning algorithm) in the relevant environment (such as MPE, SMAC, etc.) provided by this platform?

### ISSUE THREAD

**Issue by QingYuanZi1024** [opendilab/DI-engine#744]

**Comment by puyuan1996** [comment]
Hello, if you wish to run your own designed algorithm in the environment provided by DI-engine, you may need to first integrate your algorithm into DI-engine. For the specific steps, you can refer to this[ tutorial](https://github.com/opendilab/LightZero/blob/main/docs/source/tutorials/algos/customize_algos_zh.md) (Note: The framework structure of LightZero is similar to DI-engine, and the relevant tutorial for DI-engine is still being written and will be completed as soon as possible.)

It's worth noting that DI-engine has implemented various types of reinforcement learning algorithms, including DQN, PPO, TD3, etc. Therefore, you can choose an existing algorithm that is most similar to your designed algorithm as the basis for modification. For instance, if your algorithm is of the Multi-Agent Reinforcement Learning (MARL) type, you can refer to this [document](https://di-engine-docs.readthedocs.io/zh-cn/latest/04_best_practice/marl_zh.html#di-engine-marl). For more algorithms, you can check [here](https://github.com/opendilab/DI-engine#algorithm-versatility).

During the process of integrating your algorithm into DI-engine, if you encounter any issues, you can give feedback by submitting an issue. Wishing you all the best!

**Comment by puyuan1996** [comment]
BTW，if you wish to use the environments supported by dizoo without fully migrating your own algorithm to the DI-engine framework, you can refer to these two documents: [ding_env usage tutorial](https://di-engine-docs.readthedocs.io/zh-cn/latest/04_best_practice/ding_env_zh.html) and [Introduction to dizoo](https://di-engine-docs.readthedocs.io/zh-cn/latest/11_dizoo/index_zh.html). These documents will help you understand the mechanism of the dizoo environments and its configuration in DI-engine.

For instance, if you want to use the MPE environment in pettingzoo, you can refer to the corresponding test file link: [test_petting_zoo_simple_spread_env](https://github.com/opendilab/DI-engine/blob/main/dizoo/petting_zoo/envs/test_petting_zoo_simple_spread_env.py#L36). Hopefully, this information will help you use the dizoo environments more smoothly. If there are any issues, feel free to raise them at any time.
