### ISSUE TITLE
what algorithm do you use to sovle the overcooked problem? MADDPG?

### ISSUE THREAD

**Issue by frandoLin** [opendilab/DI-engine#750]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```

**Comment by PaParaZz1** [comment]
We have not add the entire training pipeline for the overcooked problem in our open-source version. We tested QMIX and MAPPO in this problem. If necessary, we can add a demo in the next release version (v0.5.1).

**Comment by frandoLin** [comment]
> We have not add the entire training pipeline for the overcooked problem in our open-source version. We tested QMIX and MAPPO in this problem. If necessary, we can add a demo in the next release version (v0.5.1).

Where can I find the training code for the overcooked problem?

**Comment by PaParaZz1** [comment]
Current repo doesn't have training code for the overcooked problem, we will add a basic demo use PPO for this environment in the next version (v0.5.1 or v0.5.2).
