### ISSUE TITLE
gym soccer是否有文档？ 其参数设置以及action的类型该如何写

### ISSUE THREAD

**Issue by Joylessss** [opendilab/DI-engine#769]
gym soccer是否有文档？ 其参数设置以及action的类型该如何写
在目前的文档里并没有代码示例

**Comment by PaParaZz1** [comment]
这个环境的中文文档在这里：[传送门](https://di-engine-docs.readthedocs.io/en/latest/13_envs/gym_soccer_zh.html)。
不过这个环境已经非常老了，请问你是为什么要用这个环境呢

**Comment by Joylessss** [comment]
> 这个环境的中文文档在这里：[传送门](https://di-engine-docs.readthedocs.io/en/latest/13_envs/gym_soccer_zh.html)。 不过这个环境已经非常老了，请问你是为什么要用这个环境呢

做单智能体混合动作空间的实验，可选的测试环境太少了

**Comment by PaParaZz1** [comment]
可以考虑我们之前开源的 [GoBigger 环境](https://github.com/opendilab/GoBigger)，里面有一个吃食物的单智能体子环境，也是混合动作空间。
