### ISSUE TITLE
record a video

### ISSUE THREAD

**Issue by zhixiongzh** [opendilab/DI-engine#770]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  v0.4.9 1.12.0 3.8.13 (default, Mar 28 2022, 11:38:47) 
  [GCC 7.5.0] linux
  ```

I follow the [tutorial](https://di-engine-docs.readthedocs.io/zh-cn/latest/13_envs/mujoco.html) to record a video using the following code
```python
from easydict import EasyDict
from dizoo.mujoco.envs import MujocoEnv
env = MujocoEnv(EasyDict({'env_id': 'Hoopper-v3' }))
env.enable_save_replay(replay_path='./video')
obs = env.reset()
while True:
    action = env.random_action()
    timestep = env.step(action)
    if timestep.done:
        print('Episode is over, eval episode return is: {}'.format(timestep.info['eval_episode_return']))
        break
```
but met the error below
```
Traceback (most recent call last):
  File "store_video_mujoco.py", line 20, in <module>
    env = MujocoEnv(EasyDict({'env_id': 'Hoopper-v3' }))
  File "/home/myuser/.conda/envs/si_mujoco/lib/python3.8/site-packages/dizoo/mujoco/envs/mujoco_env.py", line 37, in __init__
    self._action_clip = cfg.action_clip
AttributeError: 'EasyDict' object has no attribute 'action_clip'
```
so I modify the code such that
```
config = MujocoEnv.default_config()
config.env_id="Hopper-v3"
env = MujocoEnv(config)
env.enable_save_replay(replay_path='./video')
obs = env.reset()
while True:
    action = env.random_action()
    timestep = env.step(action)
    if timestep.done:
        print('Episode is over, eval episode return is: {}'.format(timestep.info['eval_episode_return']))
        break
```

there is still an error
```
Unknown encoder 'libx264'
ERROR: VideoRecorder encoder failed: None
ERROR: VideoRecorder encoder failed: None
ERROR: VideoRecorder encoder failed: None
ERROR: VideoRecorder encoder failed: None
ERROR: VideoRecorder encoder exited with status 1
Episode is over, eval episode return is: 15.903695570099208
```
Could I ask how to fix this?

**Comment by zhixiongzh** [comment]
I solve this by removing the ffmpeg packge from conda environment, refer to [this ](https://blog.csdn.net/weixin_40679158/article/details/121779993)

**Comment by zjowowen** [comment]
Hi, thanks for your information.
We will fix the errors in the document soon.

For installing rendering related dependencies, please use 'pip install -e .[common_env,video]'.
For installing OpenGL related dependencies, please refer to installation guide in dockerfile [https://github.com/opendilab/DI-engine/blob/main/docker/Dockerfile.env#L14](url).
