### ISSUE TITLE
Implementation of Mean-Field MARL algorithm

### ISSUE THREAD

**Issue by openRiemann** [opendilab/DI-engine#773]
Thanks for the amazing project!

Can you provide the implementation of algorithm from paper [Mean Field Multi-Agent Reinforcement Learning](http://proceedings.mlr.press/v80/yang18d/yang18d.pdf)? The official implementation from [mlii/mfrl](https://github.com/mlii/mfrl) is kind of old-fashioned.

**Comment by PaParaZz1** [comment]
Thanks for your interests! We will add this algorithm into our RoadMap and implement it in a few weeks.

**Comment by PaParaZz1** [comment]
We have updated the related docs in this PR (https://github.com/opendilab/DI-engine-docs/pull/271)

**Comment by PaParaZz1** [comment]
We have added this algorithm in #782.
