### ISSUE TITLE
混合动作空间环境，PPO使用gae_estimator报错

### ISSUE THREAD

**Issue by dajianer** [opendilab/DI-engine#784]
我的环境是混合动作空间的，在仿照例子运行PPO时，gae_estimator报错：RuntimeError: Could not infer dtype of EasyDict
![image](https://github.com/opendilab/DI-engine/assets/55743926/73f3b3ca-d107-41da-92b6-381bcd1ff491)
查看源码发现这个函数不支持混合动作空间，请问应该怎么解决呢

**Comment by zjowowen** [comment]
谢谢你发现了这个问题。这个 Bug 是因为组件的修改导致的不兼容。你可以根据这个 Pull Request 中的修改方法来更新这部分的代码，并重新运行这个例子。
[https://github.com/opendilab/DI-engine/pull/786](url)

**Comment by zjowowen** [comment]
混合动作空间的配置文件可以参考：
[https://github.com/zjowowen/DI-engine/blob/main/dizoo/gym_hybrid/config/gym_hybrid_hppo_config.py](url)

**Comment by PaParaZz1** [comment]
我们已经在 #786 中修复了这个问题
