### ISSUE TITLE
question for SMAC

### ISSUE THREAD

**Issue by bihanbihan** [opendilab/DI-engine#792]
when i train smac_5m6m_mappo_config.py,smac_5m6m_masac_config.py,and smac_5m6m_madqn_config.py.how can i get the battle win rate of these methods?i dont get the battle win rate when i train these models,and in eval period,it also only have the boolean result for battle win or battle false.

**Comment by PaParaZz1** [comment]
The win rate is calculated by the average result of `n_evaluator_episode` games' boolean results (win/lose).

For example, if `n_evaluator_episode=4`, the win rate could be 0.75 when games' boolean results are `[1, 0, 1, 1]`

**Comment by bihanbihan** [comment]
eval_episode_return [0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0,                                        
                          0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0,                                    
                          1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0,                                    
                          1.0, 1.0]                           this is the part of training log,so is it mean the win rate is calculate by eval_episode_return? 17/32=0.53125

**Comment by PaParaZz1** [comment]
> eval_episode_return [0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0] this is the part of training log,so is it mean the win rate is calculate by eval_episode_return? 17/32=0.53125

Yes, the win rate is calculated by this rule and shown as `eval_episode_return`
