### ISSUE TITLE
马里奥代码咨询

### ISSUE THREAD

**Issue by wenxueliu** [opendilab/DI-engine#803]
[dizoo/mario/mario_dqn_example.py](https://github.com/opendilab/DI-engine/blob/main/dizoo/mario/mario_dqn_example.py) 和 [dizoo/mario/mario_dqn_main.py](https://github.com/opendilab/DI-engine/blob/main/dizoo/mario/mario_dqn_main.py) 的区别是什么

**Comment by PaParaZz1** [comment]
DI-engine 中现存两种训练流程，即我们所称的新旧 pipeline，前者多以 `xxx_example.py` 命名命名，后者多以 `xxx_main.py` 形式命名，具体两者的设计区别可以参考[文档](https://di-engine-docs.readthedocs.io/zh-cn/latest/04_best_practice/diff_in_new_pipeline_zh.html)
