### ISSUE TITLE
No example for Trading Environments

### ISSUE THREAD

**Issue by eramosr16** [opendilab/DI-engine#810]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ x] documentation request
    + [ ] new feature request
- [x ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [ x] I have mentioned version numbers, operating system and environment, where applicable:

I went over the examples folder and I see multiple examples of agents learning from the existent environments but there is not example of an agent using this: https://github.com/opendilab/DI-engine/tree/main/dizoo/gym_anytrading

I tried based on current examples and no luck

**Comment by Cloud-Pku** [comment]
There is a [tutorial](https://colab.research.google.com/drive/1IKfjfyb0PSyTranJemvve2V38_JUs6yB?usp=sharing) for gym-anytrading.
