### ISSUE TITLE
Unexpected increase in memory overhead and Multi-GPU guidance in custom environments

### ISSUE THREAD

**Issue by WangJuan6** [opendilab/DI-engine#820]
Dear Author,

Sorry to bother you, I have two questions:

Q1: unexpected increase in memory overhead
I am currently using `memory_profiler` to monitor memory overhead in my code. I execute the script using the command `mprof run ding/mario/maro_dqn_main.py`, and I plot the memory overhead curve by `mprof plot mprofile_*.dat`:
![Figure_1](https://github.com/user-attachments/assets/bbdd5286-f8b5-4864-9a2e-7aed66bc9193)
![Figure_3](https://github.com/user-attachments/assets/632169e1-0105-4431-a295-42cc7d027afa)
However, I’ve noticed that the memory overhead increases unexpectedly. 

Q2: Multi-GPU guidance for the custom environment
I am attempting to use the Multi-GPU setting in the custom environment, but I encountered an error mentioned in [another GitHub issue](https://github.com/opendilab/DI-engine/issues/66):
`raise RuntimeError("please indicate rank explicitly in dist_init method")`
Could you please provide a demo or guidance on how to perform Multi-GPU training in a custom environment?

Thank you for your assistance!

Best regards,
Juan

**Comment by PaParaZz1** [comment]
You can enable DistributedDataParallel (DDP) multi-gpu training following this [example](https://github.com/opendilab/DI-engine/blob/main/dizoo/atari/config/serial/spaceinvaders/spaceinvaders_dqn_config_multi_gpu_ddp.py). Here we need to first initialize related multi-gpu settings like `rank` and `world_size`.

For the problem of the increasing memory overhead, I think it may be related to the increasing number of examples in replay buffer.

**Comment by WangJuan6** [comment]
Thank you for your response. I will review my code
