### ISSUE TITLE
No Hidden Size List for ContinuousQAC?

### ISSUE THREAD

**Issue by MarkHolmstrom** [opendilab/DI-engine#826]
Hello,

I am replicating a TD3 implementation in DI-engine and noticed the actor and critic hidden sizes are forced to be integers for vector observations. Is there a reason for not allowing the MLP to have heterogeneous hidden layer sizes?

**Comment by PaParaZz1** [comment]
In our experiments for TD3, we mainly test its performance on the classical MuJoCo environments. For this case, the simple design is suitable and enough to acquire excellent performance. And it often needs more complicated normalization and network initialization techniques when using more complex network. Therefore, we use current design for `ContinuousQAC`.

If you have other demands for your environment, you can imitate `ContinuousQAC` class and implement your own QAC network.
