### ISSUE TITLE
gfootball no obs module

### ISSUE THREAD

**Issue by wenyu427** [opendilab/DI-engine#834]
ModuleNotFoundError: No module named 'dizoo.gfootball.envs.ob

**Comment by PaParaZz1** [comment]
The module you mentioned `dizoo.gfootball.envs.obs` exists [here](https://github.com/opendilab/DI-engine/tree/main/dizoo/gfootball/envs/obs).

Maybe you should check the installation and import codes. If you still have problems, you can add your related screenshot in this issue. We will provide further support.
