### ISSUE TITLE
Bugreport:  运行ptz_simple_spread_qmix_config.py会出错

### ISSUE THREAD

**Issue by agdlfksdhasdoi** [opendilab/DI-engine#836]
运行ptz_simple_spread_qmix_config.py会出错
措施：修改petting_zoo_simple_spread_env.py 
    由（在195行）obs_n = self._process_obs(obs) 改为obs_n = self._process_obs(obs[0])

**Comment by puyuan1996** [comment]
您好，我在本地运行是没有报错的，我的版本是 pettingzoo==1.22.3 numpy==1.24.3，请你查看一下你的版本，是否是由于版本不一致导致的问题呢？

**Comment by agdlfksdhasdoi** [comment]
我的     di-engine 0.5.2          pettingzoo 1.24.3           numpy 1.23.1，在这样的版本下就报错了

**Comment by puyuan1996** [comment]
您好，我确认这个问题是由 PettingZoo 版本引起的。在最新版本 (1.24.3) 中，reset 和 step 函数返回的 obs 是一个二维元组。第一维表示当前队伍所有智能体的观测信息，第二维表示对方队伍所有智能体的观测信息（如果是合作环境，例如 simple_spread，则对应的 obs 是一个空字典）。感谢您的反馈，我们会在近期更新代码以适配最新版本的 PettingZoo。
