### ISSUE TITLE
Bug in reset method

### ISSUE THREAD

**Issue by neal2164** [opendilab/DI-engine#846]
https://github.com/opendilab/DI-engine/blob/de9ada00245be1e5ca7b5b106e3b779881d0c3c7/ding/model/wrapper/model_wrappers.py#L76

pass should be replaced by code like
`if hasattr(self._model, 'reset'):
            return self._model.reset(data_id=data_id, *args, **kwargs)`

This bug can cause many issues.

For instance, if a model is first wrapped by the HiddenStatesWrapper then the EpsGreedyWrapper, calling reset method will not reset states.

**Comment by PaParaZz1** [comment]
Thanks for your feedback, we have fixed this problem in the similar way you mentioned. The nesting problem between multiple model wrappers is indeed a challenging matter.
