### ISSUE TITLE
LSTM Layer normalization

### ISSUE THREAD

**Issue by neal2164** [opendilab/DI-engine#849]
https://github.com/opendilab/DI-engine/blob/765b8fb0d15092027dcc5b9b511c919059e1516b/ding/torch_utils/network/rnn.py#L230

Layer normalization is applied to c before taking tanh for h calculation in the original paper: equation (22) of https://arxiv.org/pdf/1607.06450. Any reason it's not done here?

**Comment by PaParaZz1** [comment]
The Layer Normalization (LN) issue you mentioned does indeed exist. Our previous version was implemented following equations (20)-(22). However, I recall that our earlier experiments suggested that LN on `c` sometimes limits the model's capacity. We will conduct an experiment on Atari using R2D2 to verify this and modify the code accordingly, adding an option to control whether LN is applied on `c`.

**Comment by neal2164** [comment]
Thanks for your reply!
